"use client";
import * as React from 'react';
import { Plus, Server, Pencil, Trash2, ChevronDown, Check } from 'lucide-react';
import { apiClient } from '../../lib/api-client';
import { useLocale } from '../../providers/locale-provider';
import { Popover, PopoverTrigger, PopoverContent } from '../../components/ui/popover';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Field, FieldLabel } from '../../components/ui/field';
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '../../components/ui/dialog';

export function BrokerSelect({value,onChange}:{value:string;onChange:(id:string)=>void}) {
 const th=useLocale()==='th';
 const [defaultBroker,setDefaultBroker]=React.useState<{url:string;username:string}|null>(null);
 const defaultLabel=(th?'Broker เริ่มต้นของระบบ':'System default broker')+(defaultBroker?' · '+defaultBroker.url:'');
 const [brokers,setBrokers]=React.useState<{id:string;name:string;url:string;username:string}[]>([]);
 const [open,setOpen]=React.useState(false),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
 const [draft,setDraft]=React.useState({name:'',host:'',port:'1883',protocol:'mqtt',path:'/mqtt',username:'',password:''});
 const [editing,setEditing]=React.useState<string|null>(null);
 const [deleting,setDeleting]=React.useState<(typeof brokers)[number]|null>(null);
 const [picker,setPicker]=React.useState(false);
 function edit(b:(typeof brokers)[number]){const url=new URL(b.url);setEditing(b.id);setDraft({name:b.name,host:url.hostname.replace(/^\[|\]$/g,''),port:url.port||(url.protocol==='mqtts:'?'8883':url.protocol==='wss:'?'8084':url.protocol==='ws:'?'8083':'1883'),protocol:url.protocol.slice(0,-1),path:url.pathname||'/mqtt',username:b.username||'',password:''});setError('');setPicker(false);setOpen(true);}
 async function remove(){if(!deleting)return;setBusy(true);setError('');try{await apiClient.delete(`/v1/mqtt-brokers/${deleting.id}`);setBrokers(old=>old.filter(b=>b.id!==deleting.id));if(value===deleting.id)onChange('');setDeleting(null);}catch(e){setError(e instanceof Error?e.message:'Unable to delete broker');}finally{setBusy(false);}}
 const id=React.useId();
 React.useEffect(()=>{apiClient.get<typeof brokers>('/v1/mqtt-brokers').then(list=>{setDefaultBroker(list.find(b=>b.id==='default')||null);setBrokers(list.filter(b=>b.id!=='default'));}).catch(e=>setError(e.message));},[]);
  async function save(){setBusy(true);setError('');try{const {password,...settings}=draft;const body=editing&&!password?settings:draft;const broker=editing?await apiClient.patch<(typeof brokers)[number]>(`/v1/mqtt-brokers/${editing}`,body):await apiClient.post<(typeof brokers)[number]>('/v1/mqtt-brokers',body);setBrokers(old=>editing?old.map(b=>b.id===editing?broker:b):[...old,broker]);onChange(broker.id);setOpen(false);setDraft({...draft,password:'',username:''});}catch(e){setError(e instanceof Error?e.message:'Unable to save broker');}finally{setBusy(false);}}return <Field><FieldLabel htmlFor={id}>MQTT Broker</FieldLabel><div className="flex items-center gap-2"><Popover open={picker} onOpenChange={setPicker}><PopoverTrigger asChild><Button id={id} type="button" variant="outline" className="h-10 min-w-0 flex-1 justify-between font-normal"><span className="truncate">{brokers.find(b=>b.id===value)?`${brokers.find(b=>b.id===value)!.name} · ${brokers.find(b=>b.id===value)!.url}`:defaultLabel}</span><ChevronDown className="size-4 shrink-0"/></Button></PopoverTrigger><PopoverContent align="start" className="w-[var(--radix-popover-trigger-width)] min-w-72 gap-1"><Button type="button" variant="ghost" className="h-10 justify-start font-normal" onClick={()=>{onChange('');setPicker(false);}}>{defaultLabel}{!value&&<Check className="ml-auto size-4"/>}</Button>{brokers.map(b=><div key={b.id} className="flex items-center rounded-md hover:bg-muted"><Button type="button" variant="ghost" className="h-10 min-w-0 flex-1 justify-start font-normal" onClick={()=>{onChange(b.id);setPicker(false);}}><span className="truncate">{b.name} · {b.url}</span>{value===b.id&&<Check className="ml-auto size-4 shrink-0"/>}</Button><Button type="button" variant="ghost" size="icon" aria-label={`${th?'แก้ไข':'Edit'} ${b.name}`} onClick={()=>edit(b)}><Pencil className="size-4"/></Button><Button type="button" variant="ghost" size="icon" className="text-destructive hover:text-destructive" aria-label={`${th?'ลบ':'Delete'} ${b.name}`} onClick={()=>{setPicker(false);setError('');setDeleting(b);}}><Trash2 className="size-4"/></Button></div>)}</PopoverContent></Popover><Button type="button" variant="outline" className="h-10 shrink-0" onClick={()=>{setEditing(null);setDraft({name:'',host:'',port:'1883',protocol:'mqtt',path:'/mqtt',username:'',password:''});setError('');setOpen(true);}}><Plus className="size-4"/>{th?'เพิ่ม Broker':'Add broker'}</Button></div>{error&&!open&&<p role="alert" className="text-sm text-destructive">{error}</p>}
 <Dialog open={open} onOpenChange={v=>{if(!busy){setOpen(v);if(!v)setDraft(d=>({...d,password:''}));}}}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-primary/10 text-primary"><Server className="size-5"/></span>{editing?(th?'แก้ไขการเชื่อมต่อ MQTT':'Edit MQTT connection'):(th?'เพิ่มการเชื่อมต่อ MQTT':'Add MQTT connection')}</DialogTitle><DialogDescription>{th?'ระบุ IP/Host และพอร์ตของ broker ที่ Gateway ส่งข้อมูลไป':'Enter the broker host and port used by the gateway.'}</DialogDescription></DialogHeader>
 <div className="grid gap-4 sm:grid-cols-2">{(['name','host','port','username','password'] as const).map(key=><Field key={key}><FieldLabel htmlFor={`${id}-${key}`}>{({name:th?'ชื่อการเชื่อมต่อ':'Connection name',host:'IP / Host',port:'Port',username:'Username',password:'Password'})[key]}{['name','host','port'].includes(key)&&<span className="text-destructive"> *</span>}</FieldLabel><Input id={`${id}-${key}`} type={key==='password'?'password':key==='port'?'number':'text'} autoComplete={key==='password'?'new-password':'off'} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></Field>)}<Field><FieldLabel htmlFor={`${id}-protocol`}>Protocol</FieldLabel><Select value={draft.protocol} onValueChange={protocol=>setDraft({...draft,protocol,port:protocol==='mqtts'?'8883':protocol.startsWith('ws')?'8083':'1883'})}><SelectTrigger id={`${id}-protocol`} className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectGroup>{['mqtt','mqtts','ws','wss'].map(p=><SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectGroup></SelectContent></Select></Field>{draft.protocol.startsWith('ws')&&<Field><FieldLabel htmlFor={`${id}-path`}>WebSocket path</FieldLabel><Input id={`${id}-path`} value={draft.path} onChange={e=>setDraft({...draft,path:e.target.value})}/></Field>}</div>
 {editing&&<p className="text-sm text-muted-foreground">{!value&&defaultBroker&&(th?`ค่าเริ่มต้นจาก backend · Username: ${defaultBroker.username||'ไม่ใช้บัญชี'} · `:`Backend default · Username: ${defaultBroker.username||'anonymous'} · `)}{th?'เว้นรหัสผ่านว่างเพื่อใช้รหัสผ่านเดิม':'Leave password blank to keep the stored password.'}</p>} {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<DialogFooter className="gap-2"><Button type="button" variant="outline" className="h-10 px-5" disabled={busy} onClick={()=>{setOpen(false);setDraft(d=>({...d,password:''}));}}>{th?'ยกเลิก':'Cancel'}</Button><Button type="button" className="h-10 px-5" disabled={busy||!draft.name||!draft.host||!draft.port} onClick={()=>void save()}>{th?'บันทึกการเชื่อมต่อ':'Save connection'}</Button></DialogFooter></DialogContent></Dialog><Dialog open={!!deleting} onOpenChange={v=>{if(!busy&&!v){setDeleting(null);setError('');}}}><DialogContent><DialogHeader><DialogTitle className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-destructive/10 text-destructive"><Trash2 className="size-5"/></span>{th?'ลบ MQTT Broker':'Delete MQTT broker'}</DialogTitle><DialogDescription>{th?`ยืนยันลบ ${deleting?.name} (${deleting?.url})? รายการที่มี Gateway ใช้งานอยู่จะลบไม่ได้`:`Delete ${deleting?.name}? Brokers in use cannot be deleted.`}</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-destructive">{error}</p>}<DialogFooter><Button type="button" variant="outline" className="h-10 px-5" disabled={busy} onClick={()=>{setDeleting(null);setError('');}}>{th?'ยกเลิก':'Cancel'}</Button><Button type="button" variant="destructive" className="h-10 px-5" disabled={busy} onClick={()=>void remove()}>{th?'ยืนยันการลบ':'Confirm delete'}</Button></DialogFooter></DialogContent></Dialog></Field>;
}
