"use client";
import * as React from 'react';
import {Pencil,Plus,Trash2} from 'lucide-react';
import {Button} from '../../components/ui/button';
import {Input} from '../../components/ui/input';
import {Textarea} from '../../components/ui/textarea';
import {Badge} from '../../components/ui/badge';
import {Field,FieldGroup,FieldLabel} from '../../components/ui/field';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '../../components/ui/dialog';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '../../components/ui/table';
import {PayloadFieldsEditor} from '../shared/payload-fields-editor';
import {assignStandardFieldRole} from '../shared/payload-field-roles';
import {PresetPicker} from './preset-picker';
import type {PayloadField,PayloadProfile,PayloadRevision} from './payload-contracts';
import {type DeviceDraft,selectDevicePreset,validateDeviceProfile} from './site-form-values';
export function DeviceFieldsTable({fields,billingSourceTag,locale,onEdit}:{fields:PayloadField[];billingSourceTag?:string;locale:string;onEdit?:(index:number)=>void}) {
 const th=locale==='th';return <div className="min-w-0 rounded-md border [&_[data-slot=table-container]]:max-h-72 [&_[data-slot=table-container]]:overflow-auto"><Table className="min-w-[780px]"><TableHeader className="sticky top-0 bg-card"><TableRow>{(th?['ฟิลด์','ชื่อ','กลุ่ม','หน่วยต้นทาง','หน่วยปลายทาง','การแปลง','หน้าที่','การจัดการ']:['Field','Name','Group','Source unit','Target unit','Conversion','Role','Actions']).map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{fields.map((field,index)=><TableRow key={field.tag}><TableCell>{field.sourceTag&&field.sourceTag!==field.tag?field.sourceTag+' → ':''}{field.tag}</TableCell><TableCell>{field.displayName}</TableCell><TableCell>{field.pollGroup}</TableCell><TableCell>{field.sourceUnit}</TableCell><TableCell>{field.targetUnit}</TableCell><TableCell>{field.conversion}</TableCell><TableCell>{billingSourceTag===(field.sourceTag??field.tag)?<Badge>{th?'แหล่งข้อมูลบิล':'Billing source'}</Badge>:field.role==='billing-import'?(th?'พลังงานสะสม':'Cumulative energy'):field.role??'—'}</TableCell><TableCell>{onEdit&&<Button type="button" variant="ghost" size="sm" aria-label={(th?'แก้ไขฟิลด์ ':'Edit field ')+field.displayName} onClick={()=>onEdit(index)}><Pencil data-icon="inline-start"/>{th?'แก้ไข':'Edit'}</Button>}</TableCell></TableRow>)}</TableBody></Table></div>;
}
export function DeviceProfileEditor({value,onChange,revisions,locale,billing=false,identityLocked=false,billingSourceTag,showPreset=true,showMetadata=true,onCatalogChange}:{value:DeviceDraft;onChange:(draft:DeviceDraft)=>void;revisions:PayloadRevision[];locale:string;billing?:boolean;identityLocked?:boolean;billingSourceTag?:string;showPreset?:boolean;showMetadata?:boolean;onCatalogChange?:(rows:PayloadRevision[])=>void}) {
 const th=locale==='th',id=React.useId();
 const [pending,setPending]=React.useState<string|null>(null),[field,setField]=React.useState<{index:number;value:PayloadField}|null>(null),[error,setError]=React.useState(''),[json,setJson]=React.useState('');
 const changeProfile=(config:PayloadProfile)=>onChange({...value,config,dirty:true,profileDirty:true});
 function choose(presetId:string,confirmed=false){const next=selectDevicePreset(value,revisions.find(r=>r.id===presetId),confirmed);if(next){onChange(next);setPending(null);}else setPending(presetId);}
 function saveField(remove=false){if(!field)return;const updated={...field.value};delete updated.role;const fields=remove?value.config.fields.filter((_,i)=>i!==field.index):field.index===value.config.fields.length?[...value.config.fields,assignStandardFieldRole(updated)]:value.config.fields.map((f,i)=>i===field.index?assignStandardFieldRole(updated):f);const config={...value.config,fields,pollGroups:[...new Set(fields.map(f=>f.pollGroup))]};const problem=validateDeviceProfile(config,billing,locale);if(problem){setError(problem);return;}changeProfile(config);setField(null);setError('');}
 return <section className="flex min-w-0 flex-col gap-4">
 {showPreset&&<PresetPicker manual billingOnly={billing} revisions={revisions.filter(r=>(!identityLocked||r.config.deviceType===value.config.deviceType)&&(!billing||r.config.deviceType!=='solar-logger'))} value={value.sourcePresetRevisionId??value.payloadProfileRevisionId} onChange={id=>choose(id)} {...(onCatalogChange?{onCatalogChange}:{})}/>}
 {showMetadata&&<FieldGroup className="grid gap-3 sm:grid-cols-2">{(['name','externalDeviceId','model','serialNumber'] as const).map((key,index)=><Field key={key}><FieldLabel htmlFor={id+key}>{(th?['ชื่ออุปกรณ์','Device ID','รุ่นอุปกรณ์','ซีเรียลจริง']:['Device name','Device ID','Model','Actual serial'])[index]}</FieldLabel><Input id={id+key} readOnly={key==='externalDeviceId'&&identityLocked} value={value[key]} onChange={e=>onChange({...value,[key]:e.target.value,dirty:true})}/></Field>)}</FieldGroup>}
 <DeviceFieldsTable fields={value.config.fields} locale={locale} {...(billingSourceTag?{billingSourceTag}:{})} onEdit={index=>{setField({index,value:structuredClone(value.config.fields[index]!)});setError('');}}/>
 <Button type="button" variant="outline" className="self-start" onClick={()=>{setField({index:value.config.fields.length,value:{tag:'',displayName:'',pollGroup:value.config.pollGroups[0]??'energy',sourceUnit:'',targetUnit:'',conversion:'identity'}});setError('');}}><Plus data-icon="inline-start"/>{th?'เพิ่มฟิลด์':'Add field'}</Button>
 <details><summary className="cursor-pointer text-sm font-medium">{th?'ขั้นสูง · JSON และกลุ่มข้อมูล':'Advanced · JSON and groups'}</summary><FieldGroup className="mt-3"><Field><FieldLabel htmlFor={id+'type'}>{th?'ประเภทอุปกรณ์':'Device type'}</FieldLabel><Input id={id+'type'} readOnly={identityLocked||billing||!!value.sourcePresetRevisionId} value={value.config.deviceType} onChange={e=>changeProfile({...value.config,deviceType:e.target.value})}/></Field><Field><FieldLabel htmlFor={id+'groups'}>{th?'กลุ่มข้อมูล (คั่นด้วยจุลภาค)':'Poll groups (comma separated)'}</FieldLabel><Input id={id+'groups'} value={value.config.pollGroups.join(',')} onChange={e=>changeProfile({...value.config,pollGroups:e.target.value.split(',').map(g=>g.trim())})}/></Field><Field><FieldLabel htmlFor={id+'json'}>JSON</FieldLabel><Textarea id={id+'json'} value={json} placeholder={JSON.stringify(value.config,null,2)} onChange={e=>setJson(e.target.value)} className="min-h-32 font-mono"/></Field><Button type="button" variant="outline" onClick={()=>{try{const parsed=JSON.parse(json) as PayloadProfile;const problem=validateDeviceProfile(parsed,billing,locale);if(problem)throw Error(problem);if((identityLocked||value.sourcePresetRevisionId)&&parsed.deviceType!==value.config.deviceType)throw Error(th?'เปลี่ยนประเภทอุปกรณ์ไม่ได้':'Device type cannot change');changeProfile(parsed);setError('');}catch(e){setError(e instanceof Error?e.message:'Invalid JSON');}}}>{th?'ใช้ JSON':'Apply JSON'}</Button></FieldGroup></details>
 {error&&!field&&<p role="alert" className="text-destructive">{error}</p>}
 <Dialog open={pending!==null} onOpenChange={open=>{if(!open)setPending(null);}}><DialogContent><DialogHeader><DialogTitle>{th?'เขียนทับค่าที่แก้ไข?':'Overwrite device edits?'}</DialogTitle><DialogDescription>{th?'ใช้ชื่อ รุ่น และฟิลด์จาก Preset ที่เลือก โดยคง Device ID และซีเรียลจริง':'Use the selected preset name, model and fields. Device ID and actual serial are retained.'}</DialogDescription></DialogHeader><DialogFooter><Button type="button" variant="outline" onClick={()=>setPending(null)}>{th?'ยกเลิก':'Cancel'}</Button><Button type="button" onClick={()=>choose(pending!,true)}>{th?'ยืนยันเขียนทับ':'Confirm overwrite'}</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={field!==null} onOpenChange={open=>{if(!open){setField(null);setError('');}}}><DialogContent className="max-h-[90svh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{th?'แก้ไขฟิลด์อุปกรณ์':'Edit device field'}</DialogTitle><DialogDescription>{value.name||value.externalDeviceId|| (th?'อุปกรณ์นี้':'This device')}</DialogDescription></DialogHeader>{field&&<><PayloadFieldsEditor singleField fields={[field.value]} onChange={fields=>setField({...field,value:fields[0]!})} onAdd={()=>{}}/><Field><FieldLabel htmlFor={id+'source'}>{th?'แท็กต้นทางใน data.values':'Source tag in data.values'}</FieldLabel><Input id={id+'source'} value={field.value.sourceTag??''} placeholder={field.value.tag} onChange={e=>{const next={...field.value};if(e.target.value)next.sourceTag=e.target.value;else delete next.sourceTag;setField({...field,value:next});}}/></Field></>}{error&&<p role="alert" className="text-destructive">{error}</p>}<DialogFooter>{field&&field.index<value.config.fields.length&&<Button type="button" variant="destructive" onClick={()=>saveField(true)}><Trash2 data-icon="inline-start"/>{th?'ลบฟิลด์':'Delete field'}</Button>}<Button type="button" variant="outline" onClick={()=>{setField(null);setError('');}}>{th?'ยกเลิก':'Cancel'}</Button><Button type="button" onClick={()=>saveField()}>{th?'บันทึกฟิลด์':'Save field'}</Button></DialogFooter></DialogContent></Dialog>
 </section>;
}
