"use client";
import * as React from 'react';
import {FileJson,Save,FlaskConical} from 'lucide-react';
import {Button} from '../../components/ui/button';
import {Input} from '../../components/ui/input';
import {Textarea} from '../../components/ui/textarea';
import {Field,FieldLabel} from '../../components/ui/field';
import {ChoiceSelect} from '../../components/ui/choice-select';
import {apiClient} from '../../lib/api-client';
import type {PayloadConfig,PayloadRevision} from './payload-contracts';
import {isBillingProfile} from './payload-contracts';
import {readPayloadSample,importedReceiveConfig,type PayloadImportPlan} from './payload-import';
const templateKey='solar.site-templates.v1';
type Template={name:string;plan:PayloadImportPlan;billingId:string};
export function PayloadImportPanel({revisions,existing,onApply,onDraft,onSample}:{revisions:PayloadRevision[];onSample?:(input:string)=>void;existing?:PayloadConfig;onDraft?:(plan:PayloadImportPlan,billingId:string)=>void;onApply:(plan:PayloadImportPlan,billingId:string)=>void|Promise<void>}){
 const [input,setInput]=React.useState(''),[topic,setTopic]=React.useState(''),[plan,setPlan]=React.useState<PayloadImportPlan|null>(null),[billingId,setBillingId]=React.useState(''),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[verified,setVerified]=React.useState(false),[result,setResult]=React.useState(''),[templates,setTemplates]=React.useState<Template[]>([]),[templateName,setTemplateName]=React.useState('');const id=React.useId();

 React.useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(templateKey)??'[]');if(Array.isArray(saved))setTemplates(saved);}catch{}},[]);
 const read=()=>{try{const next=readPayloadSample(JSON.parse(input),topic,revisions,existing?.externalSiteId&&existing.externalGatewayId?{siteId:existing.externalSiteId,gatewayId:existing.externalGatewayId}:undefined);
 if(existing)next.devices=next.devices.map(d=>{const registered=existing.devices.find(e=>e.externalDeviceId===d.sourceId||existing.receiveRevision.config.deviceAliases.some(a=>a.source===d.sourceId&&a.target===e.externalDeviceId));return registered?{...d,externalDeviceId:registered.externalDeviceId,payloadProfileRevisionId:registered.profileRevisionId,serialNumber:registered.serialNumber??'',model:registered.model??d.model}:d;});
 const selectedBilling=next.devices.find(d=>{const r=revisions.find(r=>r.id===d.payloadProfileRevisionId);return r&&isBillingProfile(r);})?.sourceId??'';if(onDraft&&!existing){onDraft({...next,receiveConfig:next.devices.every(d=>d.payloadProfileRevisionId)?importedReceiveConfig(next,revisions):next.receiveConfig},selectedBilling);onSample?.(input);}
 setPlan(next);setBillingId(next.devices.find(d=>(()=>{const r=revisions.find(r=>r.id===d.payloadProfileRevisionId);return r&&isBillingProfile(r);})())?.sourceId??'');setError('');setResult('');setVerified(false);
 }catch(e){setError(e instanceof Error?e.message:'อ่าน JSON ไม่สำเร็จ');}};
 const update=(index:number,patch:Partial<PayloadImportPlan['devices'][number]>)=>{if(plan)setPlan({...plan,devices:plan.devices.map((d,i)=>i===index?{...d,...patch}:d)});setVerified(false);setResult('');};
 const validate=async()=>{if(!plan)return;setBusy(true);setError('');setVerified(false);try{
 const inferred=importedReceiveConfig(plan,revisions);const previous=existing?.receiveRevision.config;const config=previous?{...previous,...inferred,fieldPaths:previous.fieldPaths,deviceAliases:[...previous.deviceAliases.filter(a=>!plan.devices.some(d=>d.sourceId===a.source)),...inferred.deviceAliases]}:inferred;const response=await apiClient.post<{messages:{status:string;reason?:string;historical?:boolean}[];ignored:number}>('/v1/sites/payload-preview',{externalSiteId:plan.siteId,externalGatewayId:plan.gatewayId,devices:plan.devices.map(d=>({externalDeviceId:d.externalDeviceId,payloadProfileRevisionId:d.payloadProfileRevisionId})),config,input:JSON.parse(input),topic:`solar/v1/sites/${plan.siteId}/gateways/${plan.gatewayId}/devices/${plan.devices[0]!.externalDeviceId}/telemetry`});
 const failed=response.messages.filter(m=>m.status!=='valid');setResult(`ผ่าน ${response.messages.length-failed.length} · ไม่ผ่าน ${failed.length} · ข้ามคำยืนยัน ${response.ignored}${response.messages.some(m=>m.historical)?' · มีข้อมูลย้อนหลัง ไม่ทำให้ไซต์ออนไลน์':''}${failed.length?' · '+failed.map(m=>m.reason).join(' / '):''}`);setVerified(!failed.length&&response.messages.length>0);
 }catch(e){setError(e instanceof Error?e.message:'ตรวจสอบไม่สำเร็จ');}finally{setBusy(false);}};
 const apply=async()=>{if(!plan)return;setError('');try{
 if(new Set(plan.devices.map(d=>d.externalDeviceId)).size!==plan.devices.length)throw Error('รหัสอุปกรณ์ต้องไม่ซ้ำ');
 if(plan.devices.some(d=>!d.name.trim()||!d.model.trim()||!d.serialNumber.trim()||!/^[-A-Za-z0-9_]{1,128}$/.test(d.externalDeviceId)||!d.payloadProfileRevisionId))throw Error('กรอกชื่อ รุ่น ซีเรียล และเลือกโปรไฟล์ให้ครบ');
 if(!existing){const meter=plan.devices.find(d=>d.sourceId===billingId);const revision=revisions.find(r=>r.id===meter?.payloadProfileRevisionId);if(!revision||!isBillingProfile(revision))throw Error('เลือกมิเตอร์หลักที่ใช้โปรไฟล์รองรับการคิดบิล');}
 setBusy(true);await onApply({...plan,receiveConfig:importedReceiveConfig(plan,revisions)},billingId);setResult('ใช้ค่าที่ตรวจสอบแล้ว');
 }catch(e){setError(e instanceof Error?e.message:'ใช้ค่าไม่สำเร็จ');}finally{setBusy(false);}};
 return <section className="space-y-4 border-t pt-5"><h3 className="flex items-center gap-2 text-sm font-semibold"><FileJson className="size-4 text-primary"/>ตั้งค่าจาก Payload ตัวอย่าง</h3>
 {!onDraft&&!!templates.length&&<Field><FieldLabel htmlFor={`${id}-template`}>แม่แบบที่บันทึกในเบราว์เซอร์นี้</FieldLabel><ChoiceSelect id={`${id}-template`} value="" onChange={e=>{const template=templates[Number(e.target.value)];if(!template)return;setPlan({...template.plan,...(existing?{siteId:existing.externalSiteId!,gatewayId:existing.externalGatewayId!,topic:`solar/v1/sites/${existing.externalSiteId}/gateways/${existing.externalGatewayId}/devices/+/telemetry`}:{}),devices:template.plan.devices.map(d=>({...d,serialNumber:''}))});setBillingId(template.billingId);setVerified(false);setInput('');setResult('เติมแม่แบบแล้ว กรุณาตรวจรหัส กรอกซีเรียล และวาง JSON ของไซต์นี้เพื่อทดสอบ');}}><option value="">เลือกแม่แบบ</option>{templates.map((t,i)=><option key={i} value={i}>{t.name}</option>)}</ChoiceSelect></Field>}
 <div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel htmlFor={`${id}-topic`}>MQTT Topic</FieldLabel><Input id={`${id}-topic`} value={topic} placeholder="solar/v1/sites/.../devices/METER-001/telemetry" onChange={e=>{setTopic(e.target.value);setPlan(null);setResult('');setVerified(false);}}/><p className="text-sm text-muted-foreground">เว้นว่างเพื่อใช้รหัสจาก JSON หรือวาง Topic จริงเพื่อเสนอการจับคู่รหัส</p></Field><Field><FieldLabel htmlFor={`${id}-json`}>JSON ตัวอย่างจาก Gateway</FieldLabel><Textarea id={`${id}-json`} value={input} className="h-48 min-h-32 max-h-[60vh] resize-y overflow-y-auto [field-sizing:fixed] font-mono" spellCheck={false} style={{fieldSizing:"fixed"}} onChange={e=>{setInput(e.target.value);setVerified(false);}}/></Field></div><Button type="button" variant="outline" disabled={busy||!input.trim()} onClick={read}>อ่านและเติมค่า</Button>
 {plan&&onDraft&&!existing&&<p role="status" className="text-sm">เติมค่าลงแบบฟอร์มแล้ว · พบ {plan.devices.length} อุปกรณ์ · {plan.devices.every(d=>d.payloadProfileRevisionId)?"จับคู่โปรไฟล์ครบ":"โปรดเลือกโปรไฟล์ที่ยังไม่พบในแบบฟอร์มด้านล่าง"}</p>}
 {plan&&(!onDraft||existing)&&<><p className="text-sm">ไซต์: {plan.siteId} · Gateway: {plan.gatewayId} · ตรวจพบ {plan.devices.length} อุปกรณ์</p><p className="break-all text-sm text-muted-foreground">Subscribe: {plan.topic} · ACK: solar/v1/sites/{plan.siteId}/gateways/{plan.gatewayId}/dataAcept</p>{plan.devices.map((d,index)=>{const pinned=existing?.devices.some(e=>e.externalDeviceId===d.externalDeviceId);return <div key={d.sourceId} className="grid gap-3 border-t pt-4 sm:grid-cols-2 xl:grid-cols-4"><Field><FieldLabel htmlFor={`${id}-${index}-name`}>ชื่ออุปกรณ์ · {d.sourceId}</FieldLabel><Input id={`${id}-${index}-name`} value={d.name} disabled={pinned} onChange={e=>update(index,{name:e.target.value})}/></Field><Field><FieldLabel htmlFor={`${id}-${index}-serial`}>ซีเรียลจริง</FieldLabel><Input id={`${id}-${index}-serial`} value={d.serialNumber} disabled={pinned} onChange={e=>update(index,{serialNumber:e.target.value})}/></Field><Field><FieldLabel htmlFor={`${id}-${index}-device`}>รหัสรับข้อมูลในระบบ</FieldLabel><Input id={`${id}-${index}-device`} value={d.externalDeviceId} disabled={pinned} onChange={e=>update(index,{externalDeviceId:e.target.value})}/></Field><Field><FieldLabel htmlFor={`${id}-${index}-profile`}>โปรไฟล์ · ต้นทาง {d.sourceProfileVersion}</FieldLabel><ChoiceSelect id={`${id}-${index}-profile`} value={d.payloadProfileRevisionId} disabled={pinned} onChange={e=>update(index,{payloadProfileRevisionId:e.target.value})}><option value="">ไม่พบเวอร์ชันตรงกัน — เลือกและทดสอบ</option>{revisions.filter(r=>r.config.id===d.sourceProfileId).map(r=><option key={r.id} value={r.id}>{r.config.displayName} · {r.version}</option>)}</ChoiceSelect></Field><Field><FieldLabel htmlFor={`${id}-${index}-model`}>รุ่นอุปกรณ์</FieldLabel><Input id={`${id}-${index}-model`} value={d.model} disabled={pinned} onChange={e=>update(index,{model:e.target.value})}/></Field></div>})}
 {!existing&&<Field><FieldLabel htmlFor={`${id}-billing`}>มิเตอร์หลักที่ใช้คิดบิล</FieldLabel><ChoiceSelect id={`${id}-billing`} value={billingId} onChange={e=>{setBillingId(e.target.value);setVerified(false);}}><option value="">เลือกมิเตอร์</option>{plan.devices.filter(d=>{const r=revisions.find(r=>r.id===d.payloadProfileRevisionId);return r&&isBillingProfile(r);}).map(d=><option key={d.sourceId} value={d.sourceId}>{d.name} · {d.externalDeviceId}</option>)}</ChoiceSelect></Field>}
 <p className="text-sm text-muted-foreground">{existing?'รายการเดิมจะคงไว้ อุปกรณ์ใหม่จะถูกเพิ่มหลังยืนยันใช้ค่า การจับคู่ต้นทางที่นำเข้าจะเพิ่มหรือแทนเฉพาะรหัสเดียวกัน':'ค่าที่อ่านได้เติมลงแบบฟอร์มแล้ว กรุณากรอกซีเรียลจริงและตรวจสอบข้อมูลก่อนบันทึก'} · การตรวจ JSON ไม่บันทึก Telemetry หรือส่ง ACK</p>
 <div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={busy||!input.trim()} onClick={()=>void validate()}><FlaskConical/>ตรวจสอบข้อมูลที่ตรวจพบ</Button><Button type="button" disabled={busy||!verified} onClick={()=>void apply()}>ยืนยันใช้ค่าที่ตรวจสอบแล้ว</Button></div>
 <details className="border-t pt-4"><summary className="cursor-pointer text-sm font-medium">บันทึกเป็นแม่แบบใช้ซ้ำ</summary><Field className="mt-3"><FieldLabel htmlFor={`${id}-template-name`}>ชื่อแม่แบบ</FieldLabel><Input id={`${id}-template-name`} value={templateName} onChange={e=>setTemplateName(e.target.value)}/></Field><p className="my-2 text-sm text-muted-foreground">เก็บเฉพาะค่าการตั้งค่าในเบราว์เซอร์นี้ ไม่เก็บค่ามิเตอร์ JSON ตัวอย่าง หรือซีเรียลจริง</p><Button type="button" variant="outline" disabled={!verified||!templateName.trim()} onClick={()=>{try{const next=[...templates.filter(t=>t.name!==templateName.trim()),{name:templateName.trim(),plan:{...plan,devices:plan.devices.map(d=>({...d,serialNumber:''}))},billingId}].slice(-20);localStorage.setItem(templateKey,JSON.stringify(next));setTemplates(next);setResult('บันทึกแม่แบบแล้ว');}catch{setError('บันทึกแม่แบบในเบราว์เซอร์ไม่สำเร็จ');}}}><Save/>บันทึกแม่แบบ</Button></details></>}
 {result&&<p role="status" className="text-sm">{result}</p>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}</section>;
}
