"use client";
import * as React from 'react';
import {apiClient} from '../../lib/api-client';
import {Button} from '../../components/ui/button';
import {DataTable} from '../../components/ui/data-table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '../../components/ui/dialog';
import {useLocale} from '../../providers/locale-provider';
import {PresetPicker} from './preset-picker';
import {PayloadImportPanel} from './payload-import-panel';
import {PayloadReceiveSettings} from './payload-receive-settings';
import {SiteBillingSource} from "./site-billing-source";
import {billingProfilePending} from "./billing-source-model";
import {DeviceProfileEditor,DeviceFieldsTable} from './device-profile-editor';
import {newDeviceDraft,draftFromDevice,deviceProfilePayload,validateDeviceDraft} from './site-form-values';
import type {PayloadConfig,PayloadDevice,PayloadRevision} from './payload-contracts';
export function ProfileSelect({revisions,value,onChange,label='Preset',onCatalogChange}:{revisions:PayloadRevision[];value:string;onChange:(id:string)=>void;label?:string;onCatalogChange?:(rows:PayloadRevision[])=>void}) {return <PresetPicker revisions={revisions} value={value} onChange={onChange} label={label} {...(onCatalogChange?{onCatalogChange}:{})}/>;}
function SavedDeviceEditor({device,revisions,onRefresh,onCatalogChange,config,focusBilling,billingSetupPending}:{device:PayloadDevice;revisions:PayloadRevision[];onRefresh:()=>void;onCatalogChange:(rows:PayloadRevision[])=>void;config:PayloadConfig;focusBilling:boolean;billingSetupPending:boolean}) {
 const locale=useLocale(),th=locale==='th';const [draft,setDraft]=React.useState(()=>draftFromDevice(device)),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[confirm,setConfirm]=React.useState(false),[activatedRevisionId,setActivatedRevisionId]=React.useState("");
 async function save(confirmed=false){const problem=validateDeviceDraft(draft,!!device.billingMeter,locale);if(problem){setError(problem);return;}if(device.billingMeter&&(draft.profileDirty||draft.payloadProfileRevisionId!==device.profileRevisionId)&&!confirmed){setConfirm(true);return;}setBusy(true);setError('');try{const saved=await apiClient.patch<{payloadProfileRevisionId:string}>(`/v1/devices/${device.id}/payload-profile`,{...deviceProfilePayload(draft),name:draft.name,model:draft.model,serialNumber:draft.serialNumber});setActivatedRevisionId(saved.payloadProfileRevisionId);setConfirm(false);setDraft({...draft,dirty:false,profileDirty:false});onRefresh();}catch(e){setError(e instanceof Error?e.message:'Unable to save');}finally{setBusy(false);}}
 return <section className="flex min-w-0 flex-col gap-4 border-t pt-4"><h3 className="text-sm font-semibold">{device.name}</h3><DeviceProfileEditor value={draft} onChange={setDraft} revisions={revisions} onCatalogChange={onCatalogChange} locale={locale} billing={!!device.billingMeter} identityLocked {...(device.billingSourceTag?{billingSourceTag:device.billingSourceTag}:{})}/><details><summary>{th?'ตัวอย่าง JSON':'Sample JSON'}</summary><pre className="max-h-64 overflow-auto text-xs">{JSON.stringify(device.fixture,null,2)}</pre></details>{error&&<p role="alert" className="text-destructive">{error}</p>}<Button type="button" className="self-start" disabled={busy||!draft.dirty&&draft.payloadProfileRevisionId===device.profileRevisionId&&draft.name===device.name&&draft.model===device.model&&draft.serialNumber===device.serialNumber} onClick={()=>void save()}>{th?'บันทึกอุปกรณ์':'Save device'}</Button><Dialog open={confirm} onOpenChange={setConfirm}><DialogContent><DialogHeader><DialogTitle>{th?'ยืนยันเปลี่ยนโปรไฟล์มิเตอร์หลัก':'Confirm main meter profile change'}</DialogTitle><DialogDescription>{th?'ใช้ Mapping ใหม่กับข้อมูลใหม่เท่านั้น ต้องยืนยันแหล่งข้อมูลบิลอีกครั้งก่อนคำนวณ':'The new mapping applies to new data. Reconfirm the billing source before calculating a bill.'}</DialogDescription></DialogHeader><DialogFooter><Button type="button" variant="outline" disabled={busy} onClick={()=>setConfirm(false)}>{th?'ยกเลิก':'Cancel'}</Button><Button type="button" disabled={busy} onClick={()=>void save(true)}>{th?'ยืนยัน':'Confirm'}</Button></DialogFooter></DialogContent></Dialog>{device.billingMeter&&<SiteBillingSource siteId={config.siteId} locale={locale} expectedProfileRevisionId={activatedRevisionId||device.profileRevisionId} refreshKey={config} profilePending={billingProfilePending({profileDirty:draft.profileDirty,selectedRevisionId:draft.payloadProfileRevisionId,persistedRevisionId:device.profileRevisionId,busy,activatedRevisionId})} receiveConfig={config.receiveRevision.config} focusOnLoad={focusBilling} setupPending={billingSetupPending} onBindingSaved={onRefresh}/>}</section>;
}
export function PayloadConnectionCard({config,onRefresh,editable=false,edgeToEdge=false,focusBilling=false,billingSetupPending=false}:{config:PayloadConfig;onRefresh:()=>void;editable?:boolean;edgeToEdge?:boolean;focusBilling?:boolean;billingSetupPending?:boolean}) {
 const locale=useLocale(),th=locale==='th';const [revisions,setRevisions]=React.useState<PayloadRevision[]>([]),[draft,setDraft]=React.useState(newDeviceDraft),[attaching,setAttaching]=React.useState(false),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
 React.useEffect(()=>{if(editable)apiClient.get<PayloadRevision[]>('/v1/settings/payload-presets').then(setRevisions).catch(e=>setError(e.message));},[editable]);
 async function attach(){const problem=validateDeviceDraft(draft,false,locale);if(problem){setError(problem);return;}setBusy(true);setError('');try{await apiClient.post(`/v1/sites/${config.siteId}/devices`,{name:draft.name,model:draft.model,serialNumber:draft.serialNumber,externalDeviceId:draft.externalDeviceId,...deviceProfilePayload(draft)});setAttaching(false);setDraft(newDeviceDraft());onRefresh();}catch(e){setError(e instanceof Error?e.message:'Unable to save');}finally{setBusy(false);}}
 return <section className={edgeToEdge?'flex min-w-0 flex-col gap-5':'flex min-w-0 flex-col gap-5 border-t pt-5'}>
 {config.devices.map(device=>editable?<SavedDeviceEditor key={device.id+'-'+device.profileRevisionId} device={device} revisions={revisions} onRefresh={onRefresh} onCatalogChange={setRevisions} config={config} focusBilling={focusBilling} billingSetupPending={billingSetupPending}/>:<section key={device.id} className="flex min-w-0 flex-col gap-3"><h3>{device.name} · {device.externalDeviceId}</h3><DeviceFieldsTable fields={device.fields??[]} locale={locale} {...(device.billingSourceTag?{billingSourceTag:device.billingSourceTag}:{})}/><details><summary>JSON</summary><pre className="max-h-64 overflow-auto">{JSON.stringify(device.fixture,null,2)}</pre></details></section>)}
 {editable&&(attaching?<section className="flex flex-col gap-4 border-t pt-4"><DeviceProfileEditor value={draft} onChange={setDraft} revisions={revisions} onCatalogChange={setRevisions} locale={locale}/><div className="flex gap-2"><Button type="button" disabled={busy} onClick={()=>void attach()}>{th?'บันทึกอุปกรณ์':'Save device'}</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>setAttaching(false)}>{th?'ยกเลิก':'Cancel'}</Button></div></section>:<Button type="button" variant="outline" className="self-start" onClick={()=>{setDraft(newDeviceDraft());setAttaching(true);setError('');}}>{th?'เพิ่มอุปกรณ์':'Add device'}</Button>)}
 {error&&<p role="alert" className="text-destructive">{error}</p>}
 {editable&&<details><summary className="cursor-pointer">{th?'การรับข้อมูลขั้นสูง':'Advanced reception'}</summary><PayloadImportPanel revisions={revisions} existing={config} onApply={async plan=>{const previous=config.receiveRevision.config;await apiClient.post(`/v1/sites/${config.siteId}/payload-import`,{baseVersion:config.receiveRevision.version,devices:plan.devices,config:{...previous,...plan.receiveConfig,fieldPaths:previous.fieldPaths,deviceAliases:[...previous.deviceAliases.filter(a=>!plan.devices.some(d=>d.sourceId===a.source)),...plan.receiveConfig.deviceAliases]}});onRefresh();}}/><PayloadReceiveSettings config={config} onRefresh={onRefresh}/></details>}
 <section className="flex flex-col gap-3"><h3>{th?'ข้อความที่ปฏิเสธ':'Rejected messages'}</h3><DataTable data={config.rejections} columns={[{accessorKey:'topic',header:'Topic'},{accessorKey:'reason',header:th?'เหตุผล':'Reason'},{accessorKey:'receivedAt',header:th?'เวลารับ':'Received'}]}/></section>
 <section className="flex flex-col gap-3"><h3>{th?'ฟิลด์ต้นทางที่ยังไม่จับคู่':'Unmapped source fields'}</h3><DataTable data={config.unmappedMessages.flatMap(m=>m.unmapped.map((f,i)=>({...f,deviceId:m.deviceId,id:m.messageId+'-'+i})))} getRowId={r=>r.id} columns={[{accessorKey:'deviceId',header:'Device'},{accessorKey:'tag',header:'Tag'},{accessorKey:'rawValue',header:'Raw value'},{accessorKey:'rawUnit',header:'Raw unit'}]}/></section>
 </section>;
}
