"use client";
import * as React from 'react';
import { apiClient } from '../../lib/api-client';
import { Button } from '../../components/ui/button';
import { Card,CardHeader,CardTitle,CardContent } from '../../components/ui/card';
import { DatePicker } from '../../components/ui/date-picker';
import { SearchInput } from '../../components/ui/search-input';
import { Label } from '../../components/ui/label';
import { DataTable } from '../../components/ui/data-table';
import { SiteEditDialog } from './site-edit-dialog';
import { PayloadConnectionCard } from './payload-connection-card';
import type { PayloadConfig } from './payload-contracts';
import { useAuth } from '../../stores/auth-store';
import { formatAppDateTime } from '../../lib/date-format';
import { useLocale } from '../../providers/locale-provider';
import { Edit,RefreshCw,Wifi,Cpu,Settings2,Database,List } from 'lucide-react';

type Config=PayloadConfig & {brokerName:string;brokerUrl:string;brokerUsername:string;pollingIntervalSeconds:number;latitude:number|null;longitude:number|null;alertRules:Record<string,unknown>};
type Sample={id:string;deviceName:string;messageId:string;tag:string;value:number;unit:string;rawValue:number;rawUnit:string;pollGroup:string;polledAt:string;receivedAt:string;quality:string;profileId:string;profileVersion:string};
type Device={id:string;name:string;model:string;serialNumber:string;externalDeviceId:string;deviceType:string};
export function SiteConfigurationDetails({siteId}:{siteId:string}) {
 const {user}=useAuth();const locale=useLocale();
 const [config,setConfig]=React.useState<Config|null>(null),[devices,setDevices]=React.useState<Device[]>([]),[mappings,setMappings]=React.useState<Record<string,unknown>[]>([]);
 const [error,setError]=React.useState(''),[historyError,setHistoryError]=React.useState(''),[edit,setEdit]=React.useState(false),[loading,setLoading]=React.useState(false);
 const [search,setSearch]=React.useState(''),[start,setStart]=React.useState(''),[end,setEnd]=React.useState(''),[page,setPage]=React.useState(1),[refresh,setRefresh]=React.useState(0);
 const [history,setHistory]=React.useState<{rows:Sample[];total:number;pageSize:number}>({rows:[],total:0,pageSize:50});
 React.useEffect(()=>{let active=true;setError('');
  Promise.all([apiClient.get<Config>(`/v1/sites/${siteId}/payload-config`),apiClient.get<Device[]>(`/v1/sites/${siteId}/devices`)]).then(async([c,d])=>{
   if(!active)return;setConfig(c);setDevices(d);
   if(!c.externalSiteId){const rows=await Promise.all(d.map(async device=>(await apiClient.get<Record<string,unknown>[]>(`/v1/devices/${device.id}/register-mappings`)).map(row=>({...row,deviceName:device.name}))));if(active)setMappings(rows.flat());}
  }).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};
 },[siteId,refresh]);
 React.useEffect(()=>{let active=true;const controller=setTimeout(()=>{
  setLoading(true);setHistoryError('');const query=new URLSearchParams({page:String(page),search,start,end});
  apiClient.get<typeof history>(`/v1/sites/${siteId}/received-data?${query}`).then(data=>{if(active)setHistory(data);}).catch(e=>{if(active){setHistory({rows:[],total:0,pageSize:50});setHistoryError(e.message);}}).finally(()=>{if(active)setLoading(false);});
 },250);return()=>{active=false;clearTimeout(controller);};},[siteId,page,search,start,end,refresh]);
 const field=(label:string,value:unknown)=><div key={label}><dt className="text-sm text-muted-foreground">{label}</dt><dd className="mt-1 break-all text-sm font-medium">{value===null||value===undefined||value===''?'—':typeof value==='object'?JSON.stringify(value):String(value)}</dd></div>;
 return <div className="space-y-5 [&_th:first-child]:pl-6 [&_td:first-child]:pl-6 [&_th:last-child]:pr-6 [&_td:last-child]:pr-6 [&_[data-slot=table-pagination]]:px-6">
  <div className="flex flex-wrap justify-end gap-2"><Button variant="outline" onClick={()=>setRefresh(r=>r+1)}><RefreshCw/>รีเฟรช</Button>{user?.role==='admin'&&<Button variant="outline" onClick={()=>setEdit(true)}><Edit/>แก้ไขไซต์และการรับข้อมูล</Button>}</div>
  {error&&<p role="alert" className="text-destructive">{error}</p>}
  {config&&<><Card><CardHeader className="py-5"><CardTitle className="flex items-center gap-2"><Wifi className="size-4 text-primary"/>Gateway และ Broker</CardTitle></CardHeader><CardContent className="pb-5"><dl className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{field('Broker',config.brokerName)}{field('ที่อยู่ Broker',config.brokerUrl)}{field('บัญชีเชื่อมต่อ',config.brokerUsername)}{field('Topic รับข้อมูล',config.subscriptionTopic)}{field('Topic ยืนยันกลับ',config.ackTopic)}{field('รอบอ่านข้อมูล (วินาที)',config.pollingIntervalSeconds)}{field('กฎแจ้งเตือน',config.alertRules)}{field('ละติจูด',config.latitude)}{field('ลองจิจูด',config.longitude)}</dl></CardContent></Card>
  <Card className="gap-0 overflow-hidden"><CardHeader className="py-5"><CardTitle className="flex items-center gap-2"><Cpu className="size-4 text-primary"/>อุปกรณ์และโปรไฟล์ที่ใช้งาน</CardTitle></CardHeader><DataTable variant="embedded" renderSearchToolbar={input=><div className="px-6 pb-4"><Label className="mb-2">ค้นหาอุปกรณ์</Label><div className="max-w-xs">{input}</div></div>} data={devices.map(d=>({...d,profileId:config.devices.find(p=>p.id===d.id)?.profileId??'ชุดรีจิสเตอร์',profileVersion:config.devices.find(p=>p.id===d.id)?.profileVersion??'—'}))} columns={[{accessorKey:'name',header:'ชื่ออุปกรณ์'},{accessorKey:'model',header:'รุ่น'},{accessorKey:'serialNumber',header:'ซีเรียล'},{accessorKey:'externalDeviceId',header:'รหัสรับข้อมูล'},{accessorKey:'profileId',header:'โปรไฟล์'},{accessorKey:'profileVersion',header:'เวอร์ชัน'}]}/></Card>
  {config.externalSiteId?<><Card><CardHeader className="py-5"><CardTitle className="flex items-center gap-2"><Settings2 className="size-4 text-primary"/>การตั้งค่ารับ Payload ที่บันทึกไว้</CardTitle></CardHeader><CardContent className="space-y-4 pb-5"><dl className="grid gap-4 sm:grid-cols-2">{field('เวอร์ชันการตั้งค่า',config.receiveRevision.version)}{field('ตำแหน่งชุดข้อความ',config.receiveRevision.config.messagesPath)}{field('รหัสไซต์ต้นทาง',config.receiveRevision.config.siteAlias)}{field('รหัส Gateway ต้นทาง',config.receiveRevision.config.gatewayAlias)}{field('จับคู่ตำแหน่ง JSON',config.receiveRevision.config.fieldPaths)}</dl></CardContent><DataTable variant="embedded" renderSearchToolbar={input=><div className="px-6 pb-4"><Label className="mb-2">ค้นหาการจับคู่</Label><div className="max-w-xs">{input}</div></div>} data={config.receiveRevision.config.deviceAliases.map(a=>({...a,sourceProfile:a.profileAlias?`${a.profileAlias.sourceId} · ${a.profileAlias.sourceVersion}`:'—',targetProfile:a.profileAlias?`${a.profileAlias.targetId} · ${a.profileAlias.targetVersion}`:'—'}))} columns={[{accessorKey:'source',header:'รหัสอุปกรณ์ต้นทาง'},{accessorKey:'target',header:'อุปกรณ์ในระบบ'},{accessorKey:'sourceProfile',header:'โปรไฟล์ต้นทาง'},{accessorKey:'targetProfile',header:'โปรไฟล์ในระบบ'}]}/></Card><PayloadConnectionCard edgeToEdge config={config} onRefresh={()=>setRefresh(r=>r+1)}/></>:<Card><CardHeader className="py-5"><CardTitle className="flex items-center gap-2"><List className="size-4 text-primary"/>การตั้งค่าชุดรีจิสเตอร์</CardTitle></CardHeader><DataTable variant="embedded" renderSearchToolbar={input=><div className="px-6 pb-4"><div className="max-w-xs">{input}</div></div>} data={mappings} columns={[{accessorKey:'deviceName',header:'อุปกรณ์'},{accessorKey:'semanticField',header:'ฟิลด์'},{accessorKey:'registerAddress',header:'ที่อยู่'},{accessorKey:'dataType',header:'ชนิดข้อมูล'},{accessorKey:'scale',header:'ตัวคูณ'},{accessorKey:'unit',header:'หน่วย'}]}/></Card>}</>}
  <Card className="gap-0 overflow-hidden"><CardHeader className="py-5"><CardTitle className="flex items-center gap-2"><Database className="size-4 text-primary"/>รายการข้อมูลที่ได้รับ</CardTitle><div className="flex flex-col gap-3 pt-2 lg:flex-row lg:items-end lg:justify-between"><div className="w-full space-y-2 lg:max-w-sm"><Label htmlFor="received-search">ค้นหาอุปกรณ์ ฟิลด์ หรือ Message ID</Label><SearchInput id="received-search" className="max-w-none" placeholder="ค้นหาอุปกรณ์ ฟิลด์ หรือ Message ID…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div><div className="grid gap-3 sm:grid-cols-2 lg:ml-auto lg:w-[30rem] lg:shrink-0"><div className="min-w-0 space-y-2"><Label htmlFor="received-start">วันที่เริ่มต้น (เวลารับ · กรุงเทพฯ)</Label><DatePicker id="received-start" value={start} max={end||undefined} onChange={value=>{setStart(value);setPage(1);}}/></div><div className="min-w-0 space-y-2"><Label htmlFor="received-end">วันที่สิ้นสุด</Label><DatePicker id="received-end" value={end} min={start||undefined} onChange={value=>{setEnd(value);setPage(1);}}/></div></div></div>{historyError&&<p role="alert" className="text-destructive">{historyError}</p>}</CardHeader>
  <DataTable variant="embedded" serverManaged data={history.rows} getRowId={r=>r.id} columns={[{accessorKey:'receivedAt',header:'เวลารับ',cell:({row})=>formatAppDateTime(row.original.receivedAt,locale)},{accessorKey:'polledAt',header:'เวลาต้นทาง',cell:({row})=>formatAppDateTime(row.original.polledAt,locale)},{accessorKey:'deviceName',header:'อุปกรณ์'},{accessorKey:'tag',header:'ฟิลด์'},{accessorKey:'value',header:'ค่าที่แปลงแล้ว'},{accessorKey:'unit',header:'หน่วย'},{accessorKey:'rawValue',header:'ค่าต้นทาง'},{accessorKey:'rawUnit',header:'หน่วยต้นทาง'},{accessorKey:'pollGroup',header:'กลุ่ม'},{accessorKey:'quality',header:'คุณภาพ'},{accessorKey:'messageId',header:'Message ID'},{accessorKey:'profileVersion',header:'เวอร์ชันโปรไฟล์'}]}/>
  <div className="flex flex-wrap items-center justify-between gap-3 border-t p-4 text-sm"><span>{loading?'กำลังโหลด…':`${history.total} รายการ · หน้า ${page} / ${Math.max(1,Math.ceil(history.total/50))}`}</span><div className="flex gap-2"><Button variant="outline" disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}>ก่อนหน้า</Button><Button variant="outline" disabled={page*50>=history.total||loading} onClick={()=>setPage(p=>p+1)}>ถัดไป</Button></div></div></Card>
  <SiteEditDialog open={edit} onOpenChange={value=>{setEdit(value);if(!value)setRefresh(r=>r+1);}} siteId={siteId}/>
 </div>;
}
