import { ConflictException, Injectable, NotFoundException } from "@nestjs/common";
export interface SchoolRecord { id: string; name: string; status: "active" | "inactive"; }
export interface SiteRecord { id: string; schoolId: string; name: string; timezone: string; status: "active" | "inactive"; }
export interface GatewayRecord { id: string; siteId: string; name: string; protocol: string; endpoint?: string; credentialRef?: string; status: "online" | "degraded" | "offline"; }
export interface DeviceRecord { id: string; gatewayId: string; name?: string; model?: string; serialNumber?: string; slaveId?: number; }
export interface BillingMeterRecord { id: string; siteId: string; deviceId: string; semanticField: "total_energy"; active: boolean; }
@Injectable()
export class AssetsService {
 private readonly schools=new Map<string,SchoolRecord>(); private readonly sites=new Map<string,SiteRecord>(); private readonly gateways=new Map<string,GatewayRecord>(); private readonly devices=new Map<string,DeviceRecord>(); private readonly meters=new Map<string,BillingMeterRecord>();
 createSchool(input:{id:string;name:string}):SchoolRecord { if(this.schools.has(input.id)) throw new ConflictException("School already exists"); const name=input.name.trim(); if(!name) throw new ConflictException("School name is required"); const r={id:input.id,name,status:"active" as const}; this.schools.set(r.id,r); return r; }
 createSite(input:{id:string;schoolId:string;name:string;timezone?:string}):SiteRecord { if(!this.schools.has(input.schoolId)) throw new NotFoundException("School not found"); if(this.sites.has(input.id)) throw new ConflictException("Site already exists"); const r={id:input.id,schoolId:input.schoolId,name:input.name.trim(),timezone:input.timezone??"Asia/Bangkok",status:"active" as const}; this.sites.set(r.id,r); return r; }
 registerGateway(input:{id:string;siteId:string;name:string;protocol:string;endpoint?:string;credentialRef?:string}):GatewayRecord { if(!this.sites.has(input.siteId)) throw new NotFoundException("Site not found"); if(this.gateways.has(input.id)) throw new ConflictException("Gateway already exists"); const r={...input,status:"offline" as const}; this.gateways.set(r.id,r); return r; }
 registerDevice(input:DeviceRecord):DeviceRecord { const gateway=this.gateways.get(input.gatewayId); if(!gateway) throw new NotFoundException("Gateway not found"); if(this.devices.has(input.id)) throw new ConflictException("Device already exists"); if(input.serialNumber && [...this.devices.values()].some(d=>d.serialNumber===input.serialNumber)) throw new ConflictException("Device serial number already exists"); this.devices.set(input.id,input); return input; }
 assignBillingMeter(input:{id:string;siteId:string;deviceId:string}):BillingMeterRecord { const site=this.sites.get(input.siteId), device=this.devices.get(input.deviceId), gateway=device&&this.gateways.get(device.gatewayId); if(!site||!device) throw new NotFoundException("Site or device not found"); if(!gateway||gateway.siteId!==site.id) throw new ConflictException("Device is outside site"); if([...this.meters.values()].some(m=>m.siteId===site.id&&m.active)) throw new ConflictException("Site already has an active Billing Meter"); const r={...input,semanticField:"total_energy" as const,active:true}; this.meters.set(r.id,r); return r; }
 listSchools():SchoolRecord[]{return [...this.schools.values()];}
}