import assert from 'node:assert/strict';
import test from 'node:test';
import {AssetsController} from './assets.controller.js';
import {DEFAULT_PAYLOAD_PROFILES} from '../telemetry/payload-profile.js';
function fixture(owner:string|null=null,profileType='energy-meter',archived=false,availableToDevice=false){const writes:{sql:string;values:any[]}[]=[];const shared=structuredClone(DEFAULT_PAYLOAD_PROFILES[0]!);const query=async(sql:string,values:any[]=[])=>{writes.push({sql,values});if(sql.includes('FROM payload_profile_revisions')&&!sql.includes('FOR UPDATE'))return {rows:[{id:'shared',config:shared,owner_device_id:owner,archived,available_to_device:availableToDevice}]};if(sql.includes('FROM devices')&&sql.includes('FOR UPDATE'))return {rows:[{id:'device',device_type:'meter',billing:true,external_device_id:'METER',profile_device_type:profileType}]};if(sql.includes('FROM gateways'))return {rows:[{id:'g',externalSiteId:'SITE',externalGatewayId:'GW'}]};return {rows:[]};};return {shared,writes,controller:new AssetsController({query,pool:{connect:async()=>({query,release(){}})}} as any,{} as any)};}
test('local activation stores immutable owned revision with shared lineage and does not rebind billing',async()=>{const f=fixture(),before=JSON.stringify(f.shared),config=structuredClone(f.shared);config.fields[0]!.displayName='Local voltage';const result=await f.controller.upgradePayloadProfile('device',{localOverrideConfig:config,sourcePresetRevisionId:'shared'} as any);assert.notEqual(result.payloadProfileRevisionId,'shared');const insert=f.writes.find(w=>w.sql.includes('INSERT INTO payload_profile_revisions'));assert.ok(insert);assert.ok(insert.sql.includes('owner_device_id'));assert.ok(insert.values.includes('device'));assert.ok(insert.values.includes('shared'));assert.equal(JSON.stringify(f.shared),before);assert.ok(!f.writes.some(w=>/UPDATE billing_meters|INSERT INTO billing_meters|UPDATE payload_profile_revisions|UPDATE payload_samples/.test(w.sql)));});
test('manual device creation accepts validated fields without shared preset',async()=>{const f=fixture();await f.controller.addDevice('site',{name:'Manual meter',model:'Editable model',serialNumber:'REAL1',externalDeviceId:'MANUAL',localOverrideConfig:f.shared} as any);assert.ok(f.writes.some(w=>w.sql.includes('INSERT INTO payload_profile_revisions')));assert.ok(f.writes.find(w=>w.sql.includes('INSERT INTO devices'))?.values.includes('Editable model'));});
test('billing local activation rejects missing cumulative billing field before persistence',async()=>{const f=fixture(),config=structuredClone(f.shared);config.fields=config.fields.filter(field=>field.role!=='billing-import');await assert.rejects(f.controller.upgradePayloadProfile('device',{localOverrideConfig:config} as any),/billing/i);assert.ok(!f.writes.some(w=>w.sql.includes('INSERT INTO payload_profile_revisions')));});

test('another device local revision cannot be selected or used as shared lineage',async()=>{const f=fixture('another-device');await assert.rejects(f.controller.upgradePayloadProfile('device',{payloadProfileRevisionId:'foreign'}),/not found/i);await assert.rejects(f.controller.upgradePayloadProfile('device',{localOverrideConfig:f.shared,sourcePresetRevisionId:'foreign'}),/not found/i);assert.ok(!f.writes.some(w=>/INSERT INTO|UPDATE devices/.test(w.sql)));});
test('profile activation preserves the exact deployed payload device type',async()=>{const f=fixture(null,'custom-meter');await assert.rejects(f.controller.upgradePayloadProfile('device',{localOverrideConfig:f.shared}),/type/i);});
test('manual local revision retains sender profile identity while receiving a unique internal identity',async()=>{const f=fixture();await f.controller.addDevice('site',{name:'Manual meter',model:'Actual model',serialNumber:'REAL',externalDeviceId:'MANUAL',localOverrideConfig:f.shared});const insert=f.writes.find(w=>w.sql.includes('INSERT INTO payload_profile_revisions'))!;const saved=JSON.parse(insert.values[3]);assert.equal(saved.sourceProfile.id,'schneider-pm2230');assert.equal(saved.sourceProfile.version,'1.0.0');assert.notEqual(saved.id,'schneider-pm2230');});

test('existing local device can participate in scoped reception imports without becoming a shared preset',async()=>{
 const config=structuredClone(DEFAULT_PAYLOAD_PROFILES[0]!),writes:string[]=[];
 const query=async(sql:string,values:any[]=[])=>{writes.push(sql);if(sql.includes('FROM payload_profile_revisions'))return {rows:[{id:'local',owner_device_id:'device',config}]};if(sql.includes('FROM gateways'))return {rows:[{id:'g',externalSiteId:'SITE',externalGatewayId:'GW'}]};if(sql.includes('FROM devices')&&sql.includes('JOIN payload_profile_revisions'))return {rows:[{externalDeviceId:'METER',profileRevisionId:'local',config}]};if(sql.includes('FROM devices')&&sql.includes('site_id=$1')&&values[0]==='site'&&values[1]==='METER')return {rows:[{id:'device'}]};return {rows:[]};};
 const c=new AssetsController({query,pool:{connect:async()=>({query,release(){}})}} as any,{} as any);
 await c.importPayloadConfiguration('site',{baseVersion:0,devices:[{name:'Existing',model:'Actual',serialNumber:'REAL',externalDeviceId:'METER',payloadProfileRevisionId:'local'}],config:{messagesPath:'payloads',deviceAliases:[]}});
 assert.ok(writes.includes('COMMIT'));assert.ok(!writes.some(sql=>sql.includes('INSERT INTO devices')));
});

test('archived shared lineage cannot be used by an unrelated device',async()=>{const f=fixture(null,'energy-meter',true,false);await assert.rejects(f.controller.upgradePayloadProfile('device',{localOverrideConfig:f.shared,sourcePresetRevisionId:'shared'}),/not found/i);});
test('already assigned archived lineage remains editable for its own device',async()=>{const f=fixture(null,'energy-meter',true,true);await f.controller.upgradePayloadProfile('device',{localOverrideConfig:f.shared,sourcePresetRevisionId:'shared'});assert.ok(f.writes.some(w=>w.sql.includes('INSERT INTO payload_profile_revisions')));});
