"use client";
import * as React from "react";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "../../components/ui/dialog";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import { apiClient } from "../../lib/api-client";
import { useAuth } from "../../stores/auth-store";
import { PaymentDialog } from "./payment-dialog";
import { FinancialEvidencePanel } from "./financial-evidence-panel";
export interface BillingDetailData {id:string;amount?:number;status:string;period?:string;periodStart?:string;periodEnd?:string;schoolName?:string;siteName?:string;consumedKwh?:number;openingEnergy?:number;closingEnergy?:number;rate?:number;paymentId?:string;paymentStatus?:string;slipUrl?:string;paidAt?:string;rejectionReason?:string;invoiceNumber?:string;receiptNumber?:string;transfers?:Array<{amount:number;paidAt:string;slipUrl:string;status?:string}>;[key:string]:any}
interface Props {open:boolean;onOpenChange:(open:boolean)=>void;billingId:string|null;initialData?:BillingDetailData|null;onUpdated?:()=>void;onOpenInvoice?:(data:any)=>void;onOpenReceipt?:(data:any)=>void}
export function BillingDetailModal({open,onOpenChange,billingId,initialData,onUpdated,onOpenInvoice,onOpenReceipt}:Props){
 const {user}=useAuth();const financial=user?.role==='owner'||user?.role==='accountant';const [data,setData]=React.useState<BillingDetailData|null>(null);const [error,setError]=React.useState('');const [message,setMessage]=React.useState('');const [busy,setBusy]=React.useState(false);const [paymentOpen,setPaymentOpen]=React.useState(false);const [reason,setReason]=React.useState('');
 const id=billingId??initialData?.id;
 const refresh=React.useCallback(async()=>{if(!id)return;setData(await apiClient.get<BillingDetailData>(`/v1/billing-cycles/${id}`));},[id]);
 React.useEffect(()=>{setData(null);setError('');setMessage('');setReason('');if(open)refresh().catch(error=>setError(error.message));},[open,refresh]);
 const verify=async(status:'approved'|'rejected')=>{if(!id)return;if(status==='rejected'&&!reason.trim()){setError('Provide a rejection reason');return;}setBusy(true);setError('');setMessage('');try{await apiClient.patch(`/v1/billing-cycles/${id}/verify-payment`,{status,rejectionReason:reason.trim()});await refresh();onUpdated?.();setMessage('Payment review saved. Receipt issuance and delivery status are tracked separately.');}catch(error:any){setError(error.message);}finally{setBusy(false);}};
 const download=async(documentId:string|undefined)=>{if(!documentId){setError('Original document is unavailable; historical documents are never regenerated');return;}setBusy(true);setError('');try{const blob=await apiClient.getBlob('/v1/documents/'+encodeURIComponent(documentId)+'/pdf');const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=documentId+'.pdf';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error:any){setError(error.message);}finally{setBusy(false);}};
 const email=async()=>{if(!id)return;setBusy(true);setError('');try{await apiClient.post(`/v1/billing-cycles/${id}/send-email`,{});setMessage('Delivery requested for the contract’s eligible school accounts. Check delivery status for the result.');await refresh();}catch(error:any){setError(error.message);}finally{setBusy(false);}};
 const transfers=data?.transfers??[];const total=transfers.filter(item=>item.status==='pending_verification'||item.status==='paid').reduce((sum,item)=>sum+Math.round(Number(item.amount)*100),0);const exact=data?.amount!==undefined&&total===Math.round(Number(data.amount)*100)&&transfers.length>0;const paid=data?.status==='paid'||data?.paymentStatus==='approved';
 return <><Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Billing details</DialogTitle><DialogDescription>Issued documents preserve their original information and attachments.</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-destructive">{error}</p>}{message&&<p role="status">{message}</p>}{data?<div className="space-y-4"><p>{data.schoolName} · {data.siteName} · {data.period}</p><p>Amount: {data.amount??'Unavailable'} THB · Status: {data.status}</p><p>Due: {data.dueDate??'Unavailable'} · Delivery: {data.deliveryStatus??'See document delivery history'}</p><div className="flex flex-wrap gap-2"><Button disabled={busy} variant="outline" onClick={()=>void download(data.invoiceId)}>ดาวน์โหลดใบแจ้งหนี้ PDF / Original invoice</Button>{paid&&<Button disabled={busy} variant="outline" onClick={()=>void download(data.receiptId)}>ดาวน์โหลดใบเสร็จ PDF / Original receipt</Button>}{financial&&<Button disabled={busy} variant="outline" onClick={()=>void email()}>Request delivery to selected accounts</Button>}{!paid&&data.status!=='cancelled'&&<Button onClick={()=>setPaymentOpen(true)}>Submit transfer evidence</Button>}</div><section className="space-y-2"><h3 className="font-semibold">Submitted transfers</h3>{transfers.length?transfers.map((item,index)=><article key={index} className="border rounded p-3"><p>Transfer {index+1}: {item.amount} THB · {item.paidAt} · {item.status}</p><a href={item.slipUrl} target="_blank" rel="noreferrer" className="underline">Open evidence</a></article>):<p>No transfer evidence available.</p>}<p>Combined amount: {(total/100).toFixed(2)} THB{!exact&&transfers.length>0?' — mismatch; financial review required':''}</p></section>{financial&&!paid&&transfers.length>0&&<section className="space-y-2"><Button disabled={busy||!exact} onClick={()=>void verify('approved')}>Approve full settlement</Button><label>Rejection reason<Input value={reason} onChange={event=>setReason(event.target.value)}/></label><Button disabled={busy} variant="outline" onClick={()=>void verify('rejected')}>Reject evidence</Button></section>}<FinancialEvidencePanel billingId={data.id} onUpdated={()=>{void refresh();onUpdated?.();}}/></div>:<p>Loading billing details…</p>}</DialogContent></Dialog><PaymentDialog open={paymentOpen} onOpenChange={setPaymentOpen} billingCycle={data} onSuccess={()=>{void refresh();onUpdated?.();}}/></>;
}
