"use client";
import * as React from "react";
import { apiClient } from "../../lib/api-client";
import { useAuth } from "../../stores/auth-store";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
interface Context {meters:Array<{id:string;deviceId:string;semanticField:string}>;corrections:Array<{id:string;requestedBy:string;financialRequestedBy?:string;status:string;reason:string;originalAmount:number;proposedAmount:number;impactAmount:number}>}
export function FinancialEvidencePanel({billingId,onUpdated}:{billingId:string;onUpdated?:()=>void}) {
 const {user}=useAuth();const financial=user?.role==='owner'||user?.role==='accountant';
 const [context,setContext]=React.useState<Context>({meters:[],corrections:[]});
 const [meter,setMeter]=React.useState('');const [sourceTime,setSourceTime]=React.useState('');const [value,setValue]=React.useState('');const [evidence,setEvidence]=React.useState('');const [reason,setReason]=React.useState('');const [error,setError]=React.useState('');const [busy,setBusy]=React.useState(false);
 const refresh=React.useCallback(()=>apiClient.get<Context>(`/v1/billing-cycles/${billingId}/evidence-context`).then(setContext),[billingId]);
 React.useEffect(()=>{if(user?.role==='admin'||financial)refresh().catch(error=>setError(error.message));},[refresh,user?.role,financial]);
 const save=async(event:React.FormEvent)=>{event.preventDefault();if(!meter||!sourceTime||value.trim()===''||!Number.isFinite(Number(value))||Number(value)<0||!evidence.trim()||!reason.trim()){setError('Meter, actual timestamp, non-negative reading, evidence and reason are required');return;}setBusy(true);setError('');try{await apiClient.post(`/v1/billing-meters/${meter}/evidence-readings`,{sourceTime:new Date(sourceTime).toISOString(),value:Number(value),evidence:evidence.trim(),reason:reason.trim()});await refresh();onUpdated?.();setEvidence('');setReason('');}catch(error:any){setError(error.message);}finally{setBusy(false);}};
 const request=async(id:string)=>{setBusy(true);setError('');try{await apiClient.patch(`/v1/financial-corrections/${id}/request`,{});await refresh();onUpdated?.();}catch(error:any){setError(error.message);}finally{setBusy(false);}};
 const approve=async(id:string)=>{setBusy(true);setError('');try{await apiClient.patch(`/v1/financial-corrections/${id}/approve`,{});await refresh();onUpdated?.();}catch(error:any){setError(error.message);}finally{setBusy(false);}};
 if(user?.role!=='admin'&&!financial)return null;
 return <section className="space-y-3 border rounded p-4"><h3 className="font-semibold">หลักฐานมิเตอร์และคำขอแก้ไข / Evidence and corrections</h3><p className="text-sm">เอกสารต้นฉบับคงเดิม ผู้อนุมัติการเงินต้องเป็นคนละคนกับผู้ยืนยันคำขอ การออกเอกสารปรับปรุงยังต้องรอนโยบายบัญชี / Original documents remain unchanged; a different financial approver is required.</p>{user?.role==='admin'&&<form onSubmit={save} className="space-y-2"><label>มิเตอร์ / Meter<select className="w-full border rounded p-2" value={meter} onChange={event=>setMeter(event.target.value)}><option value="">เลือกมิเตอร์ / Select meter</option>{context.meters.map(item=><option key={item.id} value={item.id}>{item.deviceId} · {item.semanticField}</option>)}</select></label><label>วันเวลาจริง (เขตเวลาของคุณ) / Actual timestamp<Input type="datetime-local" value={sourceTime} onChange={event=>setSourceTime(event.target.value)}/></label><label>ค่าที่อ่านได้จริง / Actual reading<Input type="number" min="0" step="any" value={value} onChange={event=>setValue(event.target.value)}/></label><label>แหล่งอ้างอิงหลักฐาน / Evidence reference<Input value={evidence} onChange={event=>setEvidence(event.target.value)}/></label><label>เหตุผล / Reason<Input value={reason} onChange={event=>setReason(event.target.value)}/></label><Button type="submit" disabled={busy}>บันทึกและอนุมัติหลักฐาน / Save and approve evidence</Button></form>}
 {context.corrections.map(item=><article className="border p-3 rounded space-y-2" key={item.id}><p>{item.reason} · {item.status}</p><p>Original {item.originalAmount} · Proposed {item.proposedAmount} · Impact {item.impactAmount} THB</p>{financial&&item.status==='pending_financial_request'&&<Button disabled={busy} onClick={()=>void request(item.id)}>ยืนยันคำขอแก้ไข / Request correction</Button>}{financial&&item.status==='pending_approval'&&<Button disabled={busy||item.financialRequestedBy===user?.id} onClick={()=>void approve(item.id)}>{item.requestedBy===user?.id?'ต้องใช้ผู้อนุมัติการเงินคนอื่น / Different approver required':'อนุมัติคำขอแก้ไข / Approve correction'}</Button>}</article>)}{error&&<p role="alert" className="text-destructive">{error}</p>}</section>;
}
