"use client";
import {useEffect,useState} from 'react';
import {apiClient} from '../../lib/api-client';
import {Button} from '../../components/ui/button';
import {Input} from '../../components/ui/input';
export function MissingReadingEvidenceForm({siteId}:{siteId:string}){
 const [meters,setMeters]=useState<Array<{id:string;deviceId:string;deviceName:string;serialNumber:string;semanticField:string}>>([]);const [meter,setMeter]=useState('');const [time,setTime]=useState('');const [value,setValue]=useState('');const [evidence,setEvidence]=useState('');const [reason,setReason]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let disposed=false;setMeters([]);setMeter('');apiClient.get<typeof meters>(`/v1/sites/${encodeURIComponent(siteId)}/billing-meters`).then(rows=>{if(!disposed)setMeters(rows);}).catch(error=>{if(!disposed)setError(error.message);});return()=>{disposed=true;};},[siteId]);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setError('');setMessage('');if(!meter||!time||!Number.isFinite(Date.parse(time))||Date.parse(time)>Date.now()||value.trim()===''||!Number.isFinite(Number(value))||Number(value)<0||!evidence.trim()||!reason.trim()){setError('ระบุมิเตอร์ วันเวลาจริง ค่าสะสมที่ไม่ติดลบ แหล่งหลักฐาน และเหตุผลให้ครบ');return;}setBusy(true);try{await apiClient.post(`/v1/billing-meters/${meter}/evidence-readings`,{sourceTime:new Date(time).toISOString(),value:Number(value),evidence:evidence.trim(),reason:reason.trim()});setMessage('บันทึกและอนุมัติหลักฐานแล้ว ระบบจะตรวจความครบถ้วนใหม่ตามรอบรายชั่วโมง ยังไม่ถือว่าออกใบแจ้งหนี้แล้ว');setValue('');setEvidence('');setReason('');}catch(error:any){setError(error.message||'บันทึกหลักฐานไม่สำเร็จ');}finally{setBusy(false);}};
 return <form onSubmit={submit} className="mt-3 space-y-3 border-t pt-3"><h3 className="font-medium">บันทึกค่าจริงจากหลักฐาน (Admin)</h3><p className="text-xs">ใช้ข้อมูลจริงเท่านั้น ไม่ประมาณค่า วันเวลาต้องอยู่ในระยะ 5 นาทีจากจุดแบ่งรอบที่ขาด หากมีทั้งค่าต้นและปลายรอบให้บันทึกแยกกัน</p><label className="block">มิเตอร์<select value={meter} onChange={event=>setMeter(event.target.value)} className="block w-full rounded border p-2"><option value="">เลือกมิเตอร์</option>{meters.map(item=><option key={item.id} value={item.id}>{item.deviceName} · {item.serialNumber} · {item.semanticField}</option>)}</select></label>{!meters.length&&<p>ยังไม่มีมิเตอร์ในรายการที่โหลด ตรวจการตั้งค่ามิเตอร์หรือข้อผิดพลาดด้านล่าง</p>}<label className="block">วันเวลาจริง (ตามเขตเวลาของอุปกรณ์ที่ใช้งาน)<Input type="datetime-local" value={time} onChange={event=>setTime(event.target.value)} required/></label><label className="block">ค่าสะสมจริง (kWh)<Input type="number" min="0" step="any" value={value} onChange={event=>setValue(event.target.value)} required/></label><label className="block">แหล่งอ้างอิงหลักฐาน<Input value={evidence} onChange={event=>setEvidence(event.target.value)} required/></label><label className="block">เหตุผล<Input value={reason} onChange={event=>setReason(event.target.value)} required/></label>{error&&<p role="alert" className="text-destructive">{error}</p>}{message&&<p role="status">{message}</p>}<Button type="submit" disabled={busy||!meters.length}>{busy?'กำลังบันทึก…':'บันทึกและอนุมัติหลักฐาน'}</Button></form>;
}
