import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {waitForHttp, deploy} from './coolify-deploy.mjs';
async function server(handler, run) { const s=createServer(handler); await new Promise(r=>s.listen(0,'127.0.0.1',r)); try {await run(`http://127.0.0.1:${s.address().port}`);} finally {s.closeAllConnections(); await new Promise(r=>s.close(r));}}
test('health polling retries unavailable endpoint and rejects exhaustion',async()=>{let calls=0;await server((q,r)=>{r.writeHead(++calls<3?503:200);r.end();},async url=>{await waitForHttp(url,{interval:1,attempts:3});assert.equal(calls,3);});await server((q,r)=>{r.writeHead(503);r.end();},url=>assert.rejects(waitForHttp(url,{interval:1,attempts:2}),/not ready/));});
const sha='a'.repeat(40), digest='sha256:'+'b'.repeat(64);
const config={token:'private-test-token',uuid:'app-test',sha,images:Object.fromEntries(['api','worker','web','mqtt','certbot'].map(n=>[n,`ghcr.io/nateekarni/solar-roof/${n}@${digest}`])),interval:1,attempts:3};
test('deploy sends immutable refs, disables push builds, waits for exact commit',async()=>{const requests=[];let polls=0;await server(async(q,r)=>{let body='';for await(const b of q)body+=b;requests.push({path:q.url,auth:q.headers.authorization,body:body?JSON.parse(body):null});r.setHeader('Content-Type','application/json');r.end(JSON.stringify(q.method==='GET'&&q.url==='/api/v1/applications/app-test'?{id:42,uuid:'app-test',git_repository:'nateekarni/solar-roof',git_branch:'main',build_pack:'dockercompose',docker_compose_location:'/infra/docker/docker-compose.staging.yml'}:q.url==='/api/v1/deployments'?[]:q.url==='/api/v1/deploy'?{deployments:[{resource_uuid:'app-test',deployment_uuid:'dep-test'}]}:q.url==='/api/v1/deployments/dep-test'?{status:++polls===1?'in_progress':'finished',commit:sha}:{}));},async base=>{await deploy({...config,base,allowLocal:true});});assert.equal(polls,2);assert.ok(requests.every(r=>r.auth==='Bearer private-test-token'));assert.equal(requests[2].body.is_auto_deploy_enabled,false);assert.equal(requests[2].body.git_commit_sha,sha);assert.deepEqual(requests[3].body.data.map(e=>e.key),['API_IMAGE','WORKER_IMAGE','WEB_IMAGE','MQTT_IMAGE','CERTBOT_IMAGE']);for(const entry of requests[3].body.data){assert.equal(entry.value,config.images[entry.key.replace('_IMAGE','').toLowerCase()]);assert.equal(entry.is_runtime,true);assert.equal(entry.is_buildtime,false);assert.equal(entry.is_literal,true);}});
test('API rejection stops before deployment and never exposes response secrets',async()=>{let calls=0;await server((q,r)=>{calls++;r.writeHead(401);r.end('private-test-token');},base=>assert.rejects(deploy({...config,base,allowLocal:true}),e=>/HTTP 401/.test(e.message)&&!e.message.includes(config.token)));assert.equal(calls,1);});
test('failed or wrong commit deployments fail closed',async()=>{for(const response of [{status:'failed',commit:sha},{status:'finished',commit:'c'.repeat(40)}])await server((q,r)=>{r.setHeader('Content-Type','application/json');r.end(JSON.stringify(q.method==='GET'&&q.url==='/api/v1/applications/app-test'?{id:42,uuid:'app-test',git_repository:'nateekarni/solar-roof',git_branch:'main',build_pack:'dockercompose',docker_compose_location:'/infra/docker/docker-compose.staging.yml'}:q.url==='/api/v1/deployments'?[]:q.url==='/api/v1/deploy'?{deployments:[{resource_uuid:'app-test',deployment_uuid:'dep-test'}]}:q.url.includes('/deployments/')?response:{}));},base=>assert.rejects(deploy({...config,base,allowLocal:true})));});
test('reject mutable image refs and insecure API before network',async()=>{await assert.rejects(deploy({...config,base:'http://coolify.example'}),/HTTPS/);await assert.rejects(deploy({...config,base:'https://coolify.example',images:{...config.images,api:'image:latest'}}),/digest/);});
test('previous active deployment blocks configuration mutation after timeout',async()=>{const mutations=[];await server((q,r)=>{if(q.method!=='GET')mutations.push(q.url);r.setHeader('Content-Type','application/json');r.end(JSON.stringify(q.url==='/api/v1/applications/app-test'?{id:42,uuid:'app-test',git_repository:'nateekarni/solar-roof',git_branch:'main',build_pack:'dockercompose',docker_compose_location:'/infra/docker/docker-compose.staging.yml'}:q.url==='/api/v1/deployments'?[{application_id:'42',status:'in_progress'}]:{}));},base=>assert.rejects(deploy({...config,base,allowLocal:true}),/active deployment/));assert.deepEqual(mutations,[]);});
test('wrong Coolify repository never mutates application',async()=>{const mutations=[];await server((q,r)=>{if(q.method!=='GET')mutations.push(q.url);r.setHeader('Content-Type','application/json');r.end(JSON.stringify(q.url==='/api/v1/applications/app-test'?{id:42,uuid:'app-test',git_repository:'someone/production',git_branch:'main',build_pack:'dockercompose',docker_compose_location:'/infra/docker/docker-compose.staging.yml'}:[]));},base=>assert.rejects(deploy({...config,base,allowLocal:true}),/target/));assert.deepEqual(mutations,[]);});
test('successful malformed API response is redacted',async()=>{await server((q,r)=>{r.setHeader('Content-Type','application/json');r.end('private-test-token is not JSON');},base=>assert.rejects(deploy({...config,base,allowLocal:true}),e=>/Invalid Coolify JSON response/.test(e.message)&&!e.message.includes('private-test-token')));});
test('outage probe requires HTTP 503 instead of accepting a healthy response',async()=>{await server((q,r)=>{r.end('healthy');},url=>assert.rejects(waitForHttp(url,{expectedStatus:503,interval:1,attempts:2}),/not ready/));await server((q,r)=>{r.writeHead(503);r.end('dependency unavailable');},url=>waitForHttp(url,{expectedStatus:503,interval:1,attempts:2}));});

test('missing or mutable managed service image rejects before any API request',async()=>{
 for(const name of ['mqtt','certbot'])for(const value of [undefined,'ghcr.io/nateekarni/solar-roof/'+name+':latest','ghcr.io/other/'+name+'@'+digest]){
  let calls=0;
  await server((q,r)=>{calls++;r.end('{}');},async base=>{
   await assert.rejects(deploy({...config,base,allowLocal:true,images:{...config.images,[name]:value}}),new RegExp('Invalid immutable image digest: '+name));
  });
  assert.equal(calls,0);
 }
});
