import Link from "next/link";
import { ArrowUpRight, Sun } from "lucide-react";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card } from "../../components/ui/card";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "../../components/ui/select";
import { Sidebar } from "../../components/navigation/sidebar";
import { Topbar } from "../../components/navigation/topbar";

const stats = [["โรงเรียนทั้งหมด", "128", "โรงเรียน", "+2 เดือนนี้", "blue"], ["โรงเรียนออนไลน์", "126", "", "98.4%", "green"], ["กำลังการผลิตติดตั้ง", "18.25", "MWp", "+0.45 MWp", "violet"], ["กำลังผลิตปัจจุบัน", "11.86", "MW", "65.1% ของที่ติดตั้ง", "teal"], ["พลังงานเดือนนี้", "82.5", "MWh", "+12.4% จากเดือนก่อน", "amber"], ["รายได้เดือนนี้", "4.82", "ล้านบาท", "+8.7% จากเดือนก่อน", "green"]] as const;
const alerts = [["Inverter INV-03", "โรงเรียนบ้านคลองสี่", "ออฟไลน์", "danger"], ["Meter MTR-12", "โรงเรียนเทศบาลวัดใหม่", "เตือน", "warning"], ["Gateway GW-07", "โรงเรียนอนุบาลเมือง", "ออฟไลน์", "danger"]] as const;

export function Dashboard() { return <div className="app-shell"><Sidebar /><div className="main-panel"><Topbar /><main className="content"><section className="stats-grid">{stats.map(([label, value, unit, note, tone]) => <Card className={`stat-card ${tone}`} key={label}><span className="stat-icon"><Sun aria-hidden="true" /></span><span className="stat-label">{label}</span><strong>{value} <em>{unit}</em></strong><small>{note}</small></Card>)}</section><section className="dashboard-grid"><Card className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">ENERGY PRODUCTION</span><h2>พลังงานผลิตสะสม</h2></div><Select defaultValue="month"><SelectTrigger aria-label="ช่วงเวลา"><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="month">เดือนนี้</SelectItem><SelectItem value="year">ปีนี้</SelectItem></SelectGroup></SelectContent></Select></div><div className="chart"><div className="chart-line" /><div className="chart-axis"><span>1 มิ.ย.</span><span>8 มิ.ย.</span><span>15 มิ.ย.</span><span>22 มิ.ย.</span><span>30 มิ.ย.</span></div></div></Card><Card className="panel alert-panel"><div className="panel-heading"><div><span className="eyebrow">LIVE HEALTH</span><h2>การแจ้งเตือนล่าสุด</h2></div><Button variant="link" asChild><Link href="/alerts">ดูทั้งหมด<ArrowUpRight data-icon="inline-end" /></Link></Button></div>{alerts.map(([title, detail, state, tone]) => <div className="alert-row" key={title}><span className={`status-dot ${tone}`} /><div><strong>{title}</strong><small>{detail}</small></div><Badge variant={tone === "danger" ? "destructive" : "secondary"} className={`badge ${tone}`}>{state}</Badge></div>)}</Card></section><section className="bottom-grid"><Card className="panel"><div className="panel-heading"><div><span className="eyebrow">SITES</span><h2>โรงเรียนที่ผลิตไฟฟ้าได้สูงสุดวันนี้</h2></div><Button variant="link" asChild><Link href="/sites">ดูทั้งหมด<ArrowUpRight data-icon="inline-end" /></Link></Button></div><div className="ranking">{["รร.บ้านคลองแสน", "รร.บ้านไผ่เมือง", "รร.เทศบาลหนองยาง", "รร.อนุบาลสาธิต"].map((name, index) => <div className="ranking-row" key={name}><span className="rank">{index + 1}</span><strong>{name}</strong><span>{["1.82", "1.74", "1.68", "1.58"][index]} MWh</span></div>)}</div></Card><Card className="panel usage-card"><span className="eyebrow">MONTHLY COLLECTION</span><h2>การเก็บเงิน</h2><div className="progress-ring"><strong>97.3%</strong><small>เก็บเงินแล้ว</small></div><div className="legend"><span><i className="green-dot" /> เก็บแล้ว 4.60 ลบ.</span><span><i className="amber-dot" /> รอดำเนินการ 0.22 ลบ.</span></div></Card></section></main></div></div>; }
