import {House,UtilityPole,ArrowRight,ArrowLeft} from 'lucide-react';
export interface PowerTopologyMeasurements {generationKw:number|null;buildingLoadKw:number|null;solarToBuildingKw:number|null;gridImportKw:number|null;gridExportKw:number|null}
function SolarRoof({className,strokeWidth=1.5}:{className?:string;strokeWidth?:number}){return <svg aria-hidden="true" viewBox="0 0 64 64" className={className} fill="none" stroke="currentColor" strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round"><path d="M6 34 31 14l27 20M13 31v24h38V31"/><path d="m18 28 13-10 16 12-29-2Z" fill="currentColor" fillOpacity=".12"/><path d="m25 23 18 2M22 27l19 2M30 19l-5 9M36 22l-4 6"/><path d="M28 55V40h9v15"/><circle cx="50" cy="11" r="4"/><path d="M50 3V1m0 20v-2m8-8h3M39 11h3m14-6 2-2m-2 14 2 2"/></svg>;}

/** Pure presentation: callers must supply actual instantaneous measurements, never inferred energy deltas. */
export function SolarPowerDiagramView({locale,measurements}:{locale:'th'|'en';measurements:PowerTopologyMeasurements}){
 const th=locale==='th';const valid=(value:number|null)=>value!==null&&Number.isFinite(value)&&value>=0;const positive=(value:number|null)=>valid(value)&&value!>0;
 const nodes=[{Icon:SolarRoof,label:th?'การผลิตโซลาร์':'Solar generation',value:measurements.generationKw},{Icon:House,label:th?'โหลดอาคาร':'Building load',value:measurements.buildingLoadKw},{Icon:UtilityPole,label:th?'โครงข่ายไฟฟ้า':'Grid',value:valid(measurements.gridImportKw)&&valid(measurements.gridExportKw)?measurements.gridImportKw!-measurements.gridExportKw!:null}];
 const flows=[{left:'33.3%',Icon:ArrowRight,value:measurements.solarToBuildingKw,label:th?'โซลาร์สู่อาคาร':'Solar to building'},{left:'66.7%',Icon:ArrowLeft,value:measurements.gridImportKw,label:th?'นำเข้าจากโครงข่าย':'Grid import'},{left:'66.7%',Icon:ArrowRight,value:measurements.gridExportKw,label:th?'ส่งออกสู่โครงข่าย':'Grid export'}];
 const hasFlow=flows.some(flow=>positive(flow.value));
 return <div><div className="relative grid grid-cols-3 gap-2 py-5 sm:gap-8"><div aria-hidden="true" className="absolute left-[16.7%] right-[16.7%] top-14 border-t-2 border-dashed border-primary/30"/>{nodes.map(({Icon,label,value},index)=><div key={label} className="relative flex min-w-0 flex-col items-center gap-3 text-center"><div className="grid size-16 place-items-center rounded-2xl border border-primary/30 bg-card text-primary sm:size-20"><Icon className="size-9 sm:size-12" strokeWidth={1.5}/></div><h3 className="text-xs font-medium sm:text-sm">{label}</h3><p className="text-lg font-semibold">{value!==null&&Number.isFinite(value)?value.toLocaleString(locale,{maximumFractionDigits:2}):'—'} <span className="text-xs font-normal text-muted-foreground">kW</span></p><span className="text-xs text-muted-foreground">{value!==null?(index===0?(th?'ค่าที่วัดได้จาก Solar logger':'Measured solar logger power'):(th?'ค่าที่วัดได้':'Measured power')):(th?'ยังไม่มีค่าที่วัดได้':'No measurements available')}</span></div>)}{flows.filter(flow=>positive(flow.value)).map(({left,Icon,label,value})=><div key={label} aria-label={label} className="absolute top-10 -translate-x-1/2 rounded-full border border-primary/30 bg-card p-1.5 text-primary sm:top-11" style={{left}}><Icon className="size-4 sm:size-5"/><span className="sr-only">{value} kW</span></div>)}</div>{hasFlow&&<div className="flex flex-wrap justify-center gap-3 text-xs text-primary">{flows.filter(flow=>positive(flow.value)).map(({Icon,label,value})=><span key={label} className="inline-flex items-center gap-1.5"><Icon className="size-3.5"/>{label}: {value!.toLocaleString(locale,{maximumFractionDigits:2})} kW</span>)}</div>}</div>;
}
