"use client";
import * as React from 'react';
import {DocumentBrand} from '../../components/brand/document-brand';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '../../components/ui/dialog';
import {Button} from '../../components/ui/button';
import {apiClient} from '../../lib/api-client';
import {useLocale} from '../../providers/locale-provider';
import {embeddedImageSource} from './document-export';
import {snapshotCompany} from './snapshot-company';
import type {DocumentPreviewData} from './document-preview-modal';
const printCss=`@page{size:A4;margin:14mm}body{font-family:Arial,sans-serif;color:#172b39;margin:0;font-size:12px}.document-brand{display:block;height:64px;width:auto;max-width:256px;object-fit:contain;margin-bottom:16px}article{width:100%;max-width:182mm;margin:auto}header{display:flex;justify-content:space-between;border-bottom:3px solid #14718a;padding-bottom:24px}h1{font-size:24px;color:#14718a}h2{font-size:17px}table{width:100%;border-collapse:collapse;margin:24px 0}th,td{padding:12px 8px;border-bottom:1px solid #dce5e9;text-align:left}th{background:#edf4f6}.right{text-align:right}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin:24px 0}.muted{color:#607481}.total{font-size:20px;text-align:right;border-top:2px solid #14718a;padding:20px 0}.signatures{display:flex;justify-content:space-between;margin-top:70px}.notice{padding:12px;background:#fff5dc}p{line-height:1.6;margin:4px 0}`;
/** Handover retains its existing HTML flow. Legal and financial originals use saved PDF artifacts. */
export function HandoverPreviewModal({open,onOpenChange,data}:{open:boolean;onOpenChange:(open:boolean)=>void;data:DocumentPreviewData}) {
 const th=useLocale()==='th';const [company,setCompany]=React.useState(snapshotCompany(undefined));const [error,setError]=React.useState('');const [exporting,setExporting]=React.useState(false);const paper=React.useRef<HTMLElement>(null);
 React.useEffect(()=>{if(!open)return;let active=true;setCompany(snapshotCompany(undefined));setError('');apiClient.get<typeof company>('/v1/settings/company').then(c=>{if(active)setCompany(c);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[open]);
 const title=th?'เอกสารส่งมอบ':'Handover';
 const html=(article=paper.current?.outerHTML||'')=>`<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><style>${printCss}</style></head><body>${article}</body></html>`;
 const print=()=>{const w=window.open('','_blank');if(!w)return;w.document.write(html());w.document.close();w.focus();w.print();};
 const download=async()=>{if(!paper.current||exporting)return;setExporting(true);try{const clone=paper.current.cloneNode(true) as HTMLElement;for(const image of clone.querySelectorAll('img'))image.src=await embeddedImageSource(image.getAttribute('src')||image.src,window.location.href);const url=URL.createObjectURL(new Blob([html(clone.outerHTML)],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${data.documentNumber||data.type}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Unable to export document');}finally{setExporting(false);}};
 const eligible=!error&&!!company.companyName;
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="w-[calc(100%-2rem)] sm:max-w-5xl max-h-[94dvh] overflow-y-auto p-0 [&_button]:min-h-11"><DialogHeader className="sticky top-0 z-10 bg-background p-4"><DialogTitle>{title}</DialogTitle><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={print} disabled={!eligible}>{th?'พิมพ์ / บันทึก PDF':'Print / Save PDF'}</Button><Button variant="outline" onClick={download} disabled={!eligible||exporting}>{th?'ดาวน์โหลดเอกสาร HTML':'Download HTML'}</Button></div></DialogHeader>
 {error?<p role="alert" className="m-6 rounded border border-destructive p-4 text-destructive">{error}</p>:<div className="overflow-x-auto bg-muted/40 p-4 sm:p-8"><article ref={paper} className="mx-auto min-h-[260mm] w-full max-w-[210mm] bg-white p-5 sm:p-12 text-slate-900 shadow"><header className="flex flex-wrap justify-between gap-6 border-b-2 border-cyan-700 pb-6"><div><DocumentBrand issued={false} company={{...company,logoUrl:company.logoUrl??null}}/><h2 className="text-lg font-bold">{company.companyName||(th?'ยังไม่ได้ตั้งค่าข้อมูลบริษัท':'Company details unavailable')}</h2><p>{company.address||'—'}</p><p>{th?'เลขประจำตัวผู้เสียภาษี':'Tax ID'} {company.taxId||'—'} {company.branch}</p><p>{company.phone} {company.email}</p></div><div className="text-right"><h1 className="text-xl font-bold text-cyan-800">{title}</h1><p>{data.documentNumber||(th?'ยังไม่ออกเลขเอกสาร':'Draft document')}</p><p>{data.issueDate?.slice(0,10)||'—'}</p></div></header><div className="grid my-6 grid-cols-1 sm:grid-cols-2 gap-6"><div><p>{data.schoolName||'—'}</p><p>{data.taxAddress||'—'}</p><p>{th?'เลขประจำตัวผู้เสียภาษี:':'Tax ID:'} {data.taxId||'—'}</p></div><div><p>{th?'ไซต์:':'Site:'} {data.siteName||'—'}</p><p>{th?'รอบบิล:':'Period:'} {data.period||'—'}</p></div></div><p>Gateway: {data.gatewaySerial||'—'}</p><p>Meter: {data.meterSerial||'—'}</p><p>COD: {data.codDate||'—'}</p><div className="signatures mt-20 flex justify-between gap-8"><p>________________________<br/>{th?'ผู้จัดทำ / Prepared by':'Prepared by'}</p><p>________________________<br/>{th?'ผู้รับเอกสาร':'Document received by'}</p></div></article></div>}</DialogContent></Dialog>;
}
