"use client";

import { notify } from "../../components/feedback/notifications";
import { t } from "@solar/i18n";
import { Checkbox } from "../../components/ui/checkbox";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../../components/ui/card";
import { Input } from "../../components/ui/input";
import { Label } from "../../components/ui/label";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "../../components/ui/select";
import { Switch } from "../../components/ui/switch";
import { Button } from "../../components/ui/button";
import { ConfirmAction } from "../../components/feedback/confirm-action";

export default function SettingsPage() {
  const save = () => notify.success(t("common.success"));
  return <section><div className="page-heading"><div><span className="eyebrow">{t("settings.eyebrow")}</span><h1>{t("settings.title")}</h1><p>{t("settings.description")}</p></div><ConfirmAction trigger={<Button type="button">{t("common.save")}</Button>} title={t("common.save")} description="ยืนยันการบันทึกการตั้งค่าระบบและการแจ้งเตือน" confirmLabel="บันทึก" onConfirm={save} /></div><div className="settings-grid"><Card className="panel setting-card"><CardHeader><CardDescription>DOCUMENT SERIES</CardDescription><CardTitle>{t("settings.documentSeries")}</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><div className="flex flex-col gap-2"><Label htmlFor="invoice-prefix">{t("settings.invoicePrefix")}</Label><Input id="invoice-prefix" value="INV-{year}-" readOnly /></div><div className="flex flex-col gap-2"><Label htmlFor="receipt-prefix">{t("settings.receiptPrefix")}</Label><Input id="receipt-prefix" value="RCT-{year}-" readOnly /></div></CardContent></Card><Card className="panel setting-card"><CardHeader><CardDescription>RETENTION</CardDescription><CardTitle>{t("settings.retention")}</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><div className="flex flex-col gap-2"><Label>{t("settings.rawTelemetry")}</Label><Select defaultValue="2"><SelectTrigger aria-label={t("settings.rawTelemetry")}><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="2">2 ปี</SelectItem></SelectGroup></SelectContent></Select></div><div className="flex flex-col gap-2"><Label>{t("settings.aggregateDocuments")}</Label><Select defaultValue="7"><SelectTrigger aria-label={t("settings.aggregateDocuments")}><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="7">7 ปี</SelectItem><SelectItem value="10">10 ปี</SelectItem></SelectGroup></SelectContent></Select></div></CardContent></Card><Card className="panel setting-card"><CardHeader><CardDescription>LOCALE & ALERTS</CardDescription><CardTitle>{t("settings.localeAlerts")}</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><div className="flex flex-col gap-2"><Label>{t("settings.language")}</Label><Select defaultValue="th"><SelectTrigger aria-label={t("settings.language")}><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="th">{t("settings.thai")}</SelectItem><SelectItem value="en">{t("settings.english")}</SelectItem></SelectGroup></SelectContent></Select></div><div className="flex items-center gap-3"><Switch id="critical-email" defaultChecked /><Label htmlFor="critical-email">{t("settings.criticalEmail")}</Label></div><div className="flex items-center gap-3"><Checkbox id="in-app" defaultChecked /><Label htmlFor="in-app">{t("settings.inApp")}</Label></div></CardContent></Card></div></section>;
}