import 'reflect-metadata';
import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { Pool } from 'pg';
import mqtt from 'mqtt';
import { config } from 'dotenv';
import { AssetsController } from '../assets/assets.controller.js';
import { MqttIngestionService } from './mqtt-ingestion.service.js';
import { DEFAULT_PAYLOAD_PROFILES } from './payload-profile.js';
import { PayloadReceptionSettings } from './payload-reception-settings.js';

test('real local MQTT + PostgreSQL bundle ACK, unit conversion, replay and partial failure', {skip:process.env.PAYLOAD_RECEIVE_INTEGRATION!=='true',timeout:30000}, async()=>{
 config({path:new URL('../../../../../.env',import.meta.url).pathname.replace(/^\/([A-Za-z]:)/,'$1'),quiet:true});
 assert.ok(['localhost','127.0.0.1'].includes(new URL(process.env.DATABASE_URL!).hostname),'Integration test requires local database');
 const suffix=randomUUID().replaceAll('-',''),schema=`payload_rx_test_${suffix}`;
 const admin=new Pool({connectionString:process.env.DATABASE_URL});
 const pool=new Pool({connectionString:process.env.DATABASE_URL,options:`-c search_path=${schema},public`});
 const receiver=mqtt.connect('mqtt://localhost:1883',{clientId:`rx-${suffix}`,reconnectPeriod:0});
 const sender=mqtt.connect('mqtt://localhost:1883',{clientId:`tx-${suffix}`,reconnectPeriod:0});
 const db={query:pool.query.bind(pool),pool};
 const acks:any[]=[];let receiveError:unknown;
 const connected=(client:mqtt.MqttClient)=>new Promise<void>((resolve,reject)=>{client.once('connect',()=>resolve());client.once('error',reject);});
 const waitFor=async(count:number)=>{const end=Date.now()+6000;while(acks.length<count&&Date.now()<end&&!receiveError)await new Promise(resolve=>setTimeout(resolve,20));if(receiveError)throw receiveError;assert.equal(acks.length,count);};
 try {
  await Promise.all([connected(receiver),connected(sender)]);
  await admin.query(`CREATE SCHEMA ${schema}`);
  for(const table of ['schools','sites','gateways','devices','payload_profile_revisions','billing_meters','payload_messages','payload_samples','telemetry_raw','payload_rejections','gateway_payload_receive_revisions'])await pool.query(`CREATE TABLE ${table} (LIKE public.${table} INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES)`);
  const siteId=randomUUID(),gatewayId=randomUUID(),meterId=randomUUID(),loggerId=randomUUID(),meterRevision=randomUUID(),loggerRevision=randomUUID();
  const site=`SITE-${suffix}`,gateway=`GW-${suffix}`;
  const topic=`solar/v1/sites/${site}/gateways/${gateway}/devices/METER-TEST/telemetry`,ackTopic=`solar/v1/sites/${site}/gateways/${gateway}/dataAcept`;
  await pool.query('INSERT INTO sites(id,school_id,name,capacity_mwp,external_site_id) VALUES($1,$2,$3,1,$4)',[siteId,randomUUID(),'Isolated reception test',site]);
  await pool.query('INSERT INTO gateways(id,site_id,name,protocol,endpoint,external_gateway_id) VALUES($1,$2,$3,\'mqtt\',$4,$3)',[gatewayId,siteId,gateway,topic.replace('/METER-TEST/','/+/')]);
  const meter={...DEFAULT_PAYLOAD_PROFILES[0]!,version:'1.0.1'},logger=DEFAULT_PAYLOAD_PROFILES[1]!;
  for(const [id,profile] of [[meterRevision,meter],[loggerRevision,logger]] as const)await pool.query('INSERT INTO payload_profile_revisions(id,profile_id,version,config) VALUES($1,$2,$3,$4)',[id,profile.id,profile.version,JSON.stringify(profile)]);
  for(const [id,name,type,external,revision] of [[meterId,'Meter','meter','METER-TEST',meterRevision],[loggerId,'Logger','logger','LOGGER-TEST',loggerRevision]])await pool.query('INSERT INTO devices(id,gateway_id,site_id,name,device_type,model,serial_number,external_device_id,payload_profile_revision_id) VALUES($1,$2,$3,$4,$5,$4,$1::uuid::text,$6,$7)',[id,gatewayId,siteId,name,type,external,revision]);
  await pool.query('INSERT INTO billing_meters(id,site_id,device_id) VALUES($1,$2,$3)',[randomUUID(),siteId,meterId]);
  const settings=new PayloadReceptionSettings(db as any);
  await settings.save(siteId,{baseVersion:0,config:{siteAlias:'SITE-001',gatewayAlias:'GW-001',deviceAliases:[{source:'METER-001',target:'METER-TEST',profileAlias:{sourceId:meter.id,sourceVersion:'1.0.0',targetId:meter.id,targetVersion:meter.version}},{source:'SMARTLOGGER-001',target:'LOGGER-TEST'}]}});
  const service=new MqttIngestionService(db as any,db as any);
  receiver.on('message',(incoming,payload)=>{void service.handleIncomingMessage(incoming,payload,receiver,null).catch(error=>{receiveError=error;});});
  sender.on('message',(_incoming,payload)=>acks.push(JSON.parse(payload.toString())));
  await Promise.all([receiver.subscribeAsync(topic,{qos:1}),sender.subscribeAsync(ackTopic,{qos:1})]);
  const bundle=JSON.parse(readFileSync(new URL('./fixtures/payload-examples-v1.1.json',import.meta.url),'utf8'));
  for(const message of Object.values(bundle.payloads) as any[])if(message.messageType==='telemetry')message.timestamps={polledAt:new Date().toISOString(),sentAt:new Date().toISOString()};
  await sender.publishAsync(topic,JSON.stringify(bundle),{qos:1,retain:false});await waitFor(4);
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM payload_messages')).rows[0].count,4);
  const provisioner=new AssetsController(db as any,{refreshSubscriptions:async()=>{},publishHardwareConfig:async()=>false} as any);
  const planned={name:'Provisioned '+suffix,schoolName:'School '+suffix,capacityMwp:0.5,gatewayName:'GW-P-'+suffix,deviceSerial:'SERIAL-P-'+suffix,payloadProfileRevisionId:meterRevision,externalSiteId:'SITE-P-'+suffix,externalGatewayId:'GW-P-'+suffix,externalDeviceId:'METER-P',additionalDevices:[{name:'Planned logger',model:'SmartLogger',serialNumber:'LOGGER-P-'+suffix,externalDeviceId:'LOGGER-P',payloadProfileRevisionId:loggerRevision}],receiveConfig:{messagesPath:'payloads',deviceAliases:[{source:'SOURCE-LOGGER',target:'LOGGER-P'}]}};
  const created=await provisioner.createSite(planned);
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM devices WHERE site_id=$1',[created.id])).rows[0].count,2);
  assert.equal((await pool.query('SELECT version FROM gateway_payload_receive_revisions r JOIN gateways g ON g.id=r.gateway_id WHERE g.site_id=$1',[created.id])).rows[0].version,1);
  await provisioner.importPayloadConfiguration(created.id,{baseVersion:1,devices:[{name:'Imported logger',model:'SmartLogger',serialNumber:'IMPORT-'+suffix,externalDeviceId:'LOGGER-IMPORT',payloadProfileRevisionId:loggerRevision}],config:{messagesPath:'payloads',deviceAliases:[{source:'NEW-SOURCE',target:'LOGGER-IMPORT'}]}});
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM devices WHERE site_id=$1',[created.id])).rows[0].count,3);
  assert.equal((await pool.query('SELECT max(version) AS version FROM gateway_payload_receive_revisions r JOIN gateways g ON g.id=r.gateway_id WHERE g.site_id=$1',[created.id])).rows[0].version,2);
  await assert.rejects(provisioner.importPayloadConfiguration(created.id,{baseVersion:2,devices:[{name:'Will roll back',model:'SmartLogger',serialNumber:'UNIQUE-'+suffix,externalDeviceId:'ROLLBACK-1',payloadProfileRevisionId:loggerRevision},{name:'Duplicate serial',model:'SmartLogger',serialNumber:'IMPORT-'+suffix,externalDeviceId:'ROLLBACK-2',payloadProfileRevisionId:loggerRevision}],config:{messagesPath:'payloads',deviceAliases:[]}}));
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM devices WHERE site_id=$1',[created.id])).rows[0].count,3);
  assert.equal((await pool.query('SELECT max(version) AS version FROM gateway_payload_receive_revisions r JOIN gateways g ON g.id=r.gateway_id WHERE g.site_id=$1',[created.id])).rows[0].version,2);
  const before=(await pool.query('SELECT count(*)::int AS count FROM sites')).rows[0].count;
  await assert.rejects(provisioner.createSite({...planned,schoolName:'Rollback '+suffix,externalSiteId:'SITE-R-'+suffix,externalGatewayId:'GW-R-'+suffix,gatewayName:'GW-R-'+suffix,deviceSerial:'SERIAL-R-'+suffix}));
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM sites')).rows[0].count,before);
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM schools WHERE name=$1',['Rollback '+suffix])).rows[0].count,0);

  assert.equal((await pool.query('SELECT count(*)::int AS count FROM payload_samples')).rows[0].count,26);
  const assets=new AssetsController(db as any,{} as any);
  const history=await assets.receivedSiteData(siteId,{});
  assert.equal(history.total,26);assert.equal(history.rows.length,26);
  const energyHistory=await assets.receivedSiteData(siteId,{search:'energy.active.import.total'});
  assert.equal(energyHistory.total,1);assert.ok(energyHistory.rows[0]);assert.equal(Number(energyHistory.rows[0].value),152430.275);
  assert.equal((await assets.receivedSiteData(siteId,{page:'2'})).rows.length,0);
  assert.equal(Number((await pool.query("SELECT value FROM payload_samples WHERE tag='energy.active.import.total'")).rows[0].value),152430.275);
  assert.equal((await pool.query('SELECT status FROM gateways')).rows[0].status,'online');
  assert.ok((await pool.query('SELECT source_payload,receive_revision_id FROM payload_messages')).rows.every(row=>row.source_payload.siteId==='SITE-001'&&row.receive_revision_id));
  const firstTimes=acks.map(ack=>ack.acceptedAt);
  await sender.publishAsync(topic,JSON.stringify(bundle),{qos:1});await waitFor(8);
  assert.deepEqual(acks.slice(4).map(ack=>ack.acceptedAt),firstTimes);
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM payload_samples')).rows[0].count,26);
  const partial=structuredClone(bundle);partial.payloads.pm2230Energy.data.units['energy.active.import.total']='A';
  await sender.publishAsync(topic,JSON.stringify(partial),{qos:1});await waitFor(11);
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM payload_rejections')).rows[0].count,1);
  // Settings changes do not reinterpret an identical retry of an already committed message.
  await settings.save(siteId,{baseVersion:1,config:{siteAlias:'DIFFERENT',gatewayAlias:'DIFFERENT'}});
  await sender.publishAsync(topic,JSON.stringify(bundle),{qos:1});await waitFor(15);
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM payload_messages')).rows[0].count,4);
  await pool.query('CREATE TABLE telemetry_archive_dirty(site_id uuid NOT NULL REFERENCES sites(id),day timestamptz NOT NULL,PRIMARY KEY(site_id,day))');
  await pool.query('CREATE TABLE telemetry_archive_scan(site_id uuid PRIMARY KEY REFERENCES sites(id),next_from timestamptz,completed boolean NOT NULL DEFAULT false)');
  await pool.query('INSERT INTO telemetry_archive_dirty VALUES($1,now())',[siteId]);
  await pool.query('INSERT INTO telemetry_archive_scan(site_id) VALUES($1)',[siteId]);
  await assets.deleteSite(siteId);
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM sites WHERE id=$1',[siteId])).rows[0].count,0);
 }finally {
  await Promise.all([receiver.endAsync(true),sender.endAsync(true)]);
  await pool.end();
  // Only the uniquely named schema created by this test is removed.
  assert.match(schema,/^payload_rx_test_[a-f0-9]{32}$/);
  await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await admin.end();
 }
});
