import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { MqttIngestionService,telemetryTopicMatches } from './mqtt-ingestion.service.js';
import { DEFAULT_PAYLOAD_PROFILES } from './payload-profile.js';
const payload=JSON.parse(readFileSync(new URL('./fixtures/payload-examples-v1.1.json',import.meta.url),'utf8')).payloads.pm2230Energy;
test('standard telemetry publishes exact dataAcept after COMMIT on gateway prefix',async()=>{
 const events:string[]=[],sent:any[]=[];const query=async(sql:string)=>{if(sql.includes('FROM devices d'))return {rows:[{deviceId:'d',siteId:'s',gatewayId:'g',externalSiteId:'SITE-001',externalGatewayId:'GW-001',externalDeviceId:'METER-001',revisionId:'r',config:DEFAULT_PAYLOAD_PROFILES[0],billing:true}]};if(sql.includes('INSERT INTO payload_messages'))return {rows:[{id:'x'}]};if(sql==='COMMIT')events.push('commit');return {rows:[]};};const db={query,pool:{connect:async()=>({query,release(){}})}};const service=new MqttIngestionService(db as any,db as any);Object.assign(service,{client:{connected:true,publish(topic:string,body:string){assert.deepEqual(events,['commit']);sent.push({topic,body:JSON.parse(body)});}}});
 await service.handleIncomingMessage('solar/v1/sites/SITE-001/gateways/GW-001/devices/METER-001/telemetry',JSON.stringify(payload));assert.equal(sent[0]?.topic,'solar/v1/sites/SITE-001/gateways/GW-001/dataAcept');assert.deepEqual(Object.keys(sent[0].body).sort(),['acceptedAt','gatewayId','lotNumber','messageId','messageType','schemaVersion','siteId','status']);
});
test('standard identifiers named config and ack remain valid while control suffix is excluded',()=>{assert.equal(telemetryTopicMatches('solar/v1/sites/config/gateways/GW/devices/+/telemetry','solar/v1/sites/config/gateways/GW/devices/ack/telemetry'),true);assert.equal(telemetryTopicMatches('energy/GW/#','energy/GW/config'),false);});
test('live canonical fields merge only billing meter fields across groups',async()=>{
 const fields=[{deviceId:'meter',deviceName:'M',tag:'energy.active.import.total',value:100,unit:'kWh',rawValue:100000,rawUnit:'Wh',polledAt:'2026-10-05T01:00:00Z',receivedAt:'2026-10-05T01:00:00Z',quality:'good',communication:'online',profileId:'p',profileVersion:'1',pollGroup:'energy',role:'billing-import',billing:true},{deviceId:'meter',deviceName:'M',tag:'power.active.total',value:12,unit:'W',rawValue:12,rawUnit:'W',polledAt:'2026-10-05T01:02:00Z',receivedAt:'2026-10-05T01:02:00Z',quality:'good',communication:'online',profileId:'p',profileVersion:'1',pollGroup:'realtime',role:'active-power',billing:true},{deviceId:'logger',tag:'solar.active_power',value:999,unit:'W',polledAt:'2026-10-05T01:03:00Z',receivedAt:'2026-10-05T01:03:00Z',billing:false}];
 for(const field of fields)field.polledAt=new Date().toISOString();
 const db={query:async(sql:string)=>({rows:sql.includes('payload_samples')?fields:[{device_id:'meter',source_time:'2026-10-05T01:02:00Z',received_time:'2026-10-05T01:02:00Z',quality:'complete',active_power_w:12,total_energy_kwh:null}]})};const service=new MqttIngestionService(db as any,db as any);const live=await service.getLatestTelemetry('s');assert.equal(live?.metrics.totalEnergy,100);assert.equal(live?.metrics.activePower,12);assert.equal(live?.canonicalFields?.length,3);assert.equal(live?.canonicalFields?.[0]?.stale,false);
});

test('logger-first telemetry stays visible when billing meter has not reported',async()=>{const db={query:async(sql:string)=>({rows:sql.includes('payload_samples')?[{deviceId:'logger',deviceName:'L',tag:'solar.active_power',value:42,unit:'W',rawValue:42,rawUnit:'W',polledAt:'2026-10-05T01:00:00Z',receivedAt:'2026-10-05T01:00:00Z',quality:'good',communication:'online',profileId:'p',profileVersion:'1',pollGroup:'plant',billing:false}]:sql.includes('FROM sites s')?[{siteName:'site',gatewayId:'g',gatewayName:'G',endpoint:'solar/v1/sites/S/gateways/G/devices/+/telemetry'}]:[]})};const service=new MqttIngestionService(db as any,db as any);const live=await service.getLatestTelemetry('s');assert.ok(live);assert.equal(live.canonicalFields?.[0]?.value,42);assert.equal(live.metrics.activePower,null);});

test('stale or poor billing fields stay canonical and cannot appear healthy in compatibility cards',async()=>{for(const mode of ['stale','bad']) {const field={deviceId:'meter',deviceName:'M',tag:'energy.active.import.total',value:100,unit:'kWh',rawValue:100000,rawUnit:'Wh',polledAt:mode==='stale'?'2020-01-01T00:00:00Z':new Date().toISOString(),receivedAt:new Date().toISOString(),quality:mode==='bad'?'bad':'good',communication:'online',profileId:'p',profileVersion:'1',pollGroup:'energy',role:'billing-import',billing:true};const db={query:async(sql:string)=>({rows:sql.includes('payload_samples')?[field]:[{device_id:'meter',source_time:new Date(),received_time:new Date(),quality:'complete',total_energy_kwh:null}]})};const live=await new MqttIngestionService(db as any,db as any).getLatestTelemetry('s');assert.equal(live?.metrics.totalEnergy,null);assert.equal(live?.canonicalFields?.[0]?.value,100);if(mode==='bad')assert.equal(live?.quality,'Bad');}});
