"use client";
import {useEffect,useState} from 'react';
import {apiClient} from '../../lib/api-client';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '../../components/ui/dialog';
import type {DocumentPreviewData} from './document-preview-modal';
type RecordRow={id:string;siteId?:string;type?:string;documentType?:string;documentNumber:string;status:string;issueDate:string};
export function FinancialPdfPreview({open,onOpenChange,data}:{open:boolean;onOpenChange:(value:boolean)=>void;data:DocumentPreviewData}){
 const [rows,setRows]=useState<RecordRow[]>([]),[selected,setSelected]=useState(''),[url,setUrl]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!open)return;let active=true;setRows([]);setSelected('');setError('');if(!data.documentId){setError('ยังไม่มีเอกสารต้นฉบับที่ออกสำหรับรายการนี้');return;}apiClient.get<{rows:RecordRow[]}>('/v1/operations/documents').then(result=>{if(!active)return;const doc=result.rows.find(row=>row.id===data.documentId);if(!doc)throw new Error('ไม่พบเอกสารที่บัญชีนี้มีสิทธิ์เข้าถึง');setRows(result.rows.filter(row=>row.siteId===doc.siteId&&(row.type??row.documentType)===(doc.type??doc.documentType)));setSelected(doc.id);}).catch(error=>{if(active)setError(error.message);});return()=>{active=false;};},[open,data.documentId]);
 useEffect(()=>{setUrl('');if(!open||!selected)return;let active=true,objectUrl='';setBusy(true);setError('');apiClient.getBlob(`/v1/documents/${selected}/pdf`).then(blob=>{if(!active)return;objectUrl=URL.createObjectURL(blob);setUrl(objectUrl);}).catch(error=>{if(active)setError(error.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[open,selected]);
 const doc=rows.find(row=>row.id===selected);
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-5xl max-h-[94vh] overflow-auto"><DialogHeader><DialogTitle>{data.type==='receipt'?'ใบเสร็จรับเงิน':'เอกสารเรียกเก็บเงิน'}</DialogTitle></DialogHeader><label>เอกสารที่ออกแล้ว<select className="ml-2 rounded border p-2" value={selected} onChange={event=>setSelected(event.target.value)} disabled={!rows.length}><option value="" disabled>เลือกเอกสาร</option>{rows.map(row=><option key={row.id} value={row.id}>{row.documentNumber} · {row.issueDate?.slice(0,10)} · {row.status}</option>)}</select></label>{busy&&<p role="status">กำลังโหลด PDF ต้นฉบับ</p>}{error&&<p role="alert">{error}</p>}{url&&<><a className="text-primary underline" href={url} download={`${(doc?.documentNumber??selected).replace(/[^a-zA-Z0-9_-]/g,'_')}.pdf`}>ดาวน์โหลด PDF ต้นฉบับ</a><iframe title="PDF ต้นฉบับ" src={url} className="h-[65vh] w-full border"/><p className="text-xs text-muted-foreground">ไฟล์เดียวกับเอกสารที่ระบบใช้แนบอีเมล หากเบราว์เซอร์ไม่แสดงตัวอย่าง สามารถดาวน์โหลดเพื่อเปิดหรือพิมพ์ได้</p></>}</DialogContent></Dialog>;
}
